/*
 Navicat Premium Data Transfer

 Source Server         : 18.162.112.84
 Source Server Type    : MySQL
 Source Server Version : 80018
 Source Host           : 18.162.112.84:3306
 Source Schema         : fisher

 Target Server Type    : MySQL
 Target Server Version : 80018
 File Encoding         : 65001

 Date: 18/12/2019 22:24:38
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book`  (
  `create_time` int(11) NULL DEFAULT NULL,
  `status` smallint(6) NULL DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `author` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `binding` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `publisher` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `pages` int(11) NULL DEFAULT NULL,
  `isbn` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `summary` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `isbn`(`isbn`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of book
-- ----------------------------
INSERT INTO `book` VALUES (1576678453, 1, 1, '庆余年·壹', '猫腻', '平装16开', '中国友谊出版公司', '28.00元', 313, '9787505724358', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的，对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img3.doubanio.com/lpic/s3207456.jpg');
INSERT INTO `book` VALUES (1576678453, 1, 2, '庆余年·陆', '猫腻', '平装', '中国友谊出版公司', '29.80元', 330, '9787505724655', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的， 对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img3.doubanio.com/lpic/s3304890.jpg');
INSERT INTO `book` VALUES (1576678453, 1, 3, '庆余年·贰', '猫腻', '平装', '中国友谊出版公司', '28.00元', 312, '9787505724365', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的， 对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img1.doubanio.com/lpic/s3207458.jpg');
INSERT INTO `book` VALUES (1576678453, 1, 4, '庆余年·伍', '猫腻', '平装', '中国友谊出版公司', '28.00元', 312, '9787505724648', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的， 对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img1.doubanio.com/lpic/s3304888.jpg');
INSERT INTO `book` VALUES (1576678453, 1, 5, '庆余年·肆', '猫腻', '平装', '中国友谊出版公司', '28.00元', 314, '9787505724471', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的， 对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img3.doubanio.com/lpic/s3207466.jpg');
INSERT INTO `book` VALUES (1576678453, 1, 6, '庆余年·叁', '猫腻', '平装', '中国友谊出版公司', '28.00元', 312, '9787505724440', '一个年轻的病人，因为一次毫不意外的经历，重生到一个完全不同的世界，成为古代庆国伯爵府一个并不光彩的私生子。修行无名功诀，踏足京都官场，继承庞大商团……范闲，包裹在他最外面的是一层金光闪闪的纸衣，纸衣下面是非常刺眼使人流泪的芥末，芥末下面是甜得发腻的奶油，奶油下面是苦涩无比的毒药壳，壳的中间却有那么一抹亮光……人都是复杂的， 对于庆国的百姓来说，看到的是他金光闪闪的外衣，对于范闲的敌人来说，看到的却是这层外衣下面辛辣的芥末……且看一个混淆了身份的私生子，将如何玩转商场、官场、战场以及婚场！\\n一部《庆余年》，缓缓道来的仿佛是一个异时空的灵魂的再生，却讲尽了这片大陆上几十年的风风雨雨。在这个叫范闲的年轻人的成长路程里，庆国几十年起伏的画卷慢慢地呈现出来。\\n几十年的历程里，我们看到的是三代风云人物的起起落落、轮转更替。两条线索，范闲的成长、叶轻眉的一生贯穿着整个小说，一明一暗，把几十年的庆国风雨尽揽其中。\\n历史慢慢地湮没掉了一些我们已经找寻不到的痕迹。历史的城墙上斑驳而模糊，在风吹雨打的岁月里渐渐看不清楚了。', 'https://img3.doubanio.com/lpic/s3207463.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 7, 'Python源码剖析', '陈儒', '平装', '电子工业出版社', '69.80元', 480, '9787121068744', '作为主流的动态语言，Python不仅简单易学、移植性好，而且拥有强大丰富的库的支持。此外，Python强大的可扩展性，让开发人员既可以非常容易地利用C/C++编写Python的扩展模块，还能将Python嵌入到C/C++程序中，为自己的系统添加动态扩展和动态编程的能力。.\\n为了更好地利用Python语言，无论是使用Python语言本身，还是将Python与C/C++交互使用，深刻理解Python的运行原理都是非常重要的。本书以CPython为研究对象，在C代码一级，深入细致地剖析了Python的实现。书中不仅包括了对大量Python内置对象的剖析，更将大量的篇幅用于对Python虚拟机及Python高级特性的剖析。通过此书，读者能够透彻地理解Python中的一般表达式、控制结构、异常机制、类机制、多线程机制、模块的动态加载机制、内存管理机制等核心技术的运行原理，同时，本书所揭示的动态语言的核心技术对于理解其他动态语言，如 Javascript、Ruby等也有较大的参考价值。..\\n本书适合于Python程序员、动态语言爱好者、C程序员阅读', 'https://img3.doubanio.com/lpic/s3435132.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 8, 'Dive Into Python', 'MarkPilgrim', 'Paperback', 'Apress', 'USD 39.99', 413, '9781590593561', 'Dive Into Python 是为有经验的程序员编写的一本 Python 书。', 'https://img3.doubanio.com/lpic/s29631790.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 9, 'Dive Into Python 3', 'MarkPilgrim', 'Paperback', 'Apress', 'USD 44.99', 360, '9781430224150', 'Mark Pilgrim\'s Dive Into Python 3 is a hands-on guide to Python 3 (the latest version of the Python language) and its differences from Python 2. As in the original book, Dive Into Python, each chapter starts with a real, complete code sample, proceeds to pick it apart and explain the pieces, and then puts it all back together in a summary at the end.\\nThis book includes:\\n* Example programs completely rewritten to illustrate powerful new concepts now available in Python 3: sets, iterators, generators, closures, comprehensions, and much more\\n* A detailed case study of porting a major library from Python 2 to Python 3\\n* A comprehensive appendix of all the syntactic and semantic changes in Python 3\\nThis is the perfect resource for you if you need to port applications to Python 3, or if you like to jump into languages fast and get going right away.\\nWhat you\'ll learn\\n* Understand Python 3 code by seeing it broken down and explained\\n* Make full use of the latest Python features such as', 'https://img3.doubanio.com/lpic/s4059293.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 10, 'Python 编程金典', 'P.J.Deitel、J.P.Liperi、B.A.Wiedermann、H.M.Deitel', '平装(无盘)', '清华大学出版社', '88.00元', 596, '9787302066422', '本书由全球著名的程序语言培训专家精心编著，解释了如何将Python用作常规用途，编写多层、客户机/服务器结构、数据库密集型、基于Internet和Web的应用程序。书中采用作者独创的“活代码”教学方式，层层揭示了Python这一程序设计语言的强大功能，并通过穿插在全书各处的屏幕输出和编程技巧与提示，帮助读者搭建良好的知识结构、养成良好的编程习惯、避免常见的编程错误以及写出高效、可靠的应用程序。', 'https://img3.doubanio.com/lpic/s1326052.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 11, 'Python for Unix and Linux System Administration', 'Noah Gift、Jeremy Jones', 'Paperback', 'O\'Reilly Media', 'USD 49.99', 458, '9780596515829', 'Python is an ideal language for solving problems, especially in Linux and Unix networks. With this pragmatic book, administrators can review various tasks that often occur in the management of these systems, and learn how Python can provide a more efficient and less painful way to handle them.\\nEach chapter in Python for Unix and Linux System Administration presents a particular administrative issue, such as concurrency or data backup, and presents Python solutions through hands-on examples. Once you finish this book, you\'ll be able to develop your own set of command-line utilities with Python to tackle a wide range of problems. Discover how this language can help you:\\n* Read text files and extract information\\n* Run tasks concurrently using the threading and forking options\\n* Get information from one process to another using network facilities\\n* Create clickable GUIs to handle large and complex utilities\\n* Monitor large clusters of machines by interacting with SNMP programmaticall', 'https://img3.doubanio.com/lpic/s3355252.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 12, 'Python基础教程', 'MagnusLieHetland', '平装', '人民邮电出版社', '69.00元', 471, '9787115230270', '本书是经典教程的全新改版，作者根据Python 3.0版本的种种变化，全面改写了书中内容，做到既能“瞻前”也能“顾后”。本书层次鲜明、结构严谨、内容翔实，特别是在最后几章，作者将前面讲述的内容应用到了10个引人入胜的项目中，并以模板的形式介绍了项目的开发过程。本书既适合初学者夯实基础，又能帮助Python程序员提升技能，即使是 Python方面的技术专家，也能从书里找到令你耳目一新的东西。', 'https://img3.doubanio.com/lpic/s4387251.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 13, 'A Byte of Python', 'SwaroopCH', '平装', 'Lulu Marketplace', 'USD 27.98', 149, '9789577296467', '\'A Byte of Python\' is a book on programming using the Python language. It serves as a tutorial or guide to the Python language for a beginner audience. If all you know about computers is how to save text files, then this is the book for you.', 'https://img3.doubanio.com/lpic/s4612135.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 14, '利用Python进行数据分析', 'WesMcKinney', '平装', '机械工业出版社', '89.00', 464, '9787111436737', '【名人推荐】\\n“科学计算和数据分析社区已经等待这本书很多年了：大量具体的实践建议，以及大量综合应用方法。本书在未来几年里肯定会成为Python领域中技术计算的权威指南。”\\n——Fernando Pérez　加州大学伯克利分校 研究科学家， IPython的创始人之一\\n【内容简介】\\n还在苦苦寻觅用Python控制、处理、整理、分析结构化数据的完整课程？本书含有大量的实践案例，你将学会如何利用各种Python库（包括NumPy、pandas、matplotlib以及IPython等）高效地解决各式各样的数据分析问题。\\n由于作者Wes McKinney是pandas库的主要作者，所以本书也可以作为利用Python实现数据密集型应用的科学计算实践指南。本书适合刚刚接触Python的分析人员以及刚刚接触科学计算的Python程序员。\\n•将IPython这个交互式Shell作为你的首要开发环境。\\n•学习NumPy（Numerical Python）的基础和高级知识。\\n•从pandas库的数据分析工具开始。\\n•利用高性能工具对数据进行加载、清理、转换、合并以及重塑。\\n•利用matplotlib创建散点图以及静态或交互式的可视化结果。\\n•利用pandas的groupby功能对数据集进行切片、切块和汇总操作。\\n•处理各种各样的时间序列数据。\\n•通过详细的案例学习如何解决Web分析、社会科学、金融学以及经•济学等领域的问题。', 'https://img3.doubanio.com/lpic/s27275372.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 15, 'Fluent Python', 'Luciano Ramalho', 'Paperback', 'O\'Reilly Media', 'USD 39.99', 768, '9781491946008', 'Learn how to write idiomatic, effective Python code by leveraging its best features. Python\'s simplicity quickly lets you become productive with it, but this often means you aren’t using everything the language has to offer. By taking you through Python’s key language features and libraries, this practical book shows you how to make your code shorter, faster, and more readable all at the same time—what experts consider Pythonic.\\nMany programmers who learn Python basics fall into the trap of reinventing the wheel because of past experience in other languages, and try to bend the language to patterns that don\'t really apply to it. Author Luciano Ramalho, a Python Software Foundation member and Python programmer for 15 years, helps you drop your accent from another language so you can code Python fluently.\\n•Learn practical applications of generators for database processing\\n•Rethink some design patterns in a Python context\\n•Examine attribute descriptors and when to use them: the key to', 'https://img3.doubanio.com/lpic/s27935775.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 16, 'Python编程快速上手', '斯维加特 (Al Sweigart)', '平装', '人民邮电出版社', 'CNY 69.00', 390, '9787115422699', '如今，人们面临的大多数任务都可以通过编写计算机软件来完成。Python是一种解释型、面向对象、动态数据类型的高级程序设计语言。通过Python编程，我们能够解决现实生活中的很多任务。\\n本书是一本面向实践的Python编程实用指南。本书的目的，不仅是介绍Python语言的基础知识，而且还通过项目实践教会读者如何应用这些知识和技能。本书的首部分介绍了基本Python编程概念，第二部分介绍了一些不同的任务，通过编写Python程序，可以让计算机自动完成它们。第二部分的每一章都有一些项目程序，供读者学习。每章的末尾还提供了一些习题和深入的实践项目，帮助读者巩固所学的知识。附录部分提供了所有习题的解答。\\n本书适合任何想要通过Python学习编程的读者，尤其适合缺乏编程基础的初学者。通过阅读本书，读者将能利用强大的编程语言和工具，并且会体会到Python编程的快乐。', 'https://img3.doubanio.com/lpic/s29400403.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 17, '从Python开始学编程', 'Vamei', '其他', '电子工业出版社', 'CNY 49.00', 208, '9787121301995', '改编自Vamei博客的《Python快速教程》。本书以Python为样本，不仅介绍了编程的基本概念，还着重讲解编程语言的主流范式：面向过程、面向对象、面向函数。读者不仅可以轻松学会Python，以后再学习其他编程语言时也会更加容易。', 'https://img1.doubanio.com/lpic/s29166309.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 18, 'Python学习手册', '[美]MarkLutz', '平装', '机械工业出版社', '89.00元', 656, '9787111267768', '《Python学习手册(第3版)》讲述了：Python可移植、功能强大、易于使用，是编写独立应用程序和脚本应用程序的理想选择。无论你是刚接触编程或者刚接触Python，通过学习《Python学习手册(第3版)》，你可以迅速高效地精通核心Python语言基础。读完《Python学习手册(第3版)》，你会对这门语言有足够的了解，从而可以在你所从事的任何应用领域中使用它。\\n《Python学习手册(第3版)》是作者根据过去10年用于教学而广为人知的培训课程的材料编写而成的。除了有许多详实说明和每章小结之外，每章还包括一个头脑风暴：这是《Python学习手册(第3版)》独特的一部分，配合以实用的练习题和复习题，让读者练习新学的技巧并测试自己的理解程度。\\n《Python学习手册(第3版)》包括：\\n类型和操作——深入讨论Python主要的内置对象类型：数字、列表和字典等。\\n语句和语法——在Python中输入代码来建立并处理对象，以及Python一般的语法模型。\\n函数——Python基本的面向过程工具，用于组织代码和重用。\\n模块——封装语句、函数以及其他工具，从而可以组织成较大的组件。\\n类和OOP——Python可选的面向对象编程工具，可用于组织程序代码从而实现定制和重用。\\n异常和工具——异常处理模型和语句，并介绍编写更大程序的开发工具。\\n讨论Python 3.0。\\n《Python学习手册(第3版)》让你对Python语言有深入而完整的了解，从而帮助你理解今后遇到的任何Python应用程序实例。如果你准备探索Google和YouTube为什么选中了Python，《Python学习手册(第3版)》就是你入门的最佳指南。', 'https://img1.doubanio.com/lpic/s3952568.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 19, 'Python Cookbook', 'Alex Martelli、Anna Ravenscroft、David Ascher', '平装', '人民邮电出版社', '99.00元', 756, '9787115222664', '本书介绍了Python应用在各个领域中的一些使用技巧和方法，从最基本的字符、文件序列、字典和排序，到进阶的面向对象编程、数据库和数据持久化、 XML处理和Web编程，再到比较高级和抽象的描述符、装饰器、元类、迭代器和生成器，均有涉及。书中还介绍了一些第三方包和库的使用，包括 Twisted、GIL、PyWin32等。本书覆盖了Python应用中的很多常见问题，并提出了通用的解决方案。书中的代码和方法具有很强的实用性，可以方便地应用到实际的项目中，并产生立竿见影的效果。尤为难得的是，本书的各位作者都具有丰富的业界实践经验，因此，本书不仅给出了对各种问题的解决方案，同时还体现了很多专家的思维方式和良好的编程习惯，与具体的细节性知识相比，这部分内容无疑是本书的精华。\\n本书适合具有一定Python基础的读者阅读参考。', 'https://img3.doubanio.com/lpic/s4357883.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 20, 'Python核心编程（第二版）', '[美]WesleyJ·Chun', '平装', '人民邮电出版社', '89.00元', 654, '9787115178503', '本书是Python开发者的完全指南——针对 Python 2.5全面升级\\n·学习专业的Python风格、最佳实践和好的编程习惯；\\n·加强对Python对象、内存模型和Python面向对象特性的深入理解；\\n·构建更有效的Web、CGI、互联网、网络和其他客户端/服务器架构应用程序及软件；\\n·学习如何使用Python中的Tkinter和其他工具来开发自己的GUI应用程序及软件；\\n·通过用C等语言编写扩展来提升Python应用程序的性能，或者通过使用多线程增强I/0相关的应用程序的能力；\\n·学习Python中有关数据库的API，以及如何在Python中使用各种不同的数据库系统，包括MySQL、Postgres和 SQLite。', 'https://img3.doubanio.com/lpic/s3140466.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 21, 'Python语言及其应用', '[美] Bill Lubanovic', '平装', '人民邮电出版社', '79.00元', 404, '9787115407092', '本书介绍Python 语言的基础知识及其在各个领域的具体应用，基于最新版本3.x。书中首先介绍了Python 语言的一些必备基本知识，然后介绍了在商业、科研以及艺术领域使用Python 开发各种应用的实例。文字简洁明了，案例丰富实用，是一本难得的Python 入门手册。', 'https://img3.doubanio.com/lpic/s28352586.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 22, 'Head First Python（中文版）', '巴里（Barry.P.）', '平装', '中国电力出版社', '68.00元', 457, '9787512322233', '你想过可以通过一本书就学会Python吗？《Head First Python(中文版)》超越枯燥的语法和甩法手册，通过一种独特的方法教你学习这种语言。你会迅速掌握Python的基础知识，然后转向持久存储、异常处理、Web开发、SQLite、数据加工和lGoogle App Engine。你还将学习如何为Android编写移动应用，这都要归功于Python为你赋予的强大能力。本书会提供充分并且完备的学习体验，帮助你成为一名真正的Python程序员。    作者巴里觉得你的时间相当宝贵，不应当过多地花费在与新概念的纠缠之中。通过应用认知科学和学习理论的最新研究成果，《Head First Python(中文版)》可以让你投入一个需要多感官参与的学习体验，这本书采用丰富直观的形式使你的大脑真正开动起来，而不是长篇累牍地说教，让你昏昏欲睡。', 'https://img3.doubanio.com/lpic/s27262723.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 23, 'Effective Python', '布雷特·斯拉特金（Brett Slatkin）', '平装', '机械工业出版社', '59', NULL, '9787111523550', '用Python编写程序，是相当容易的，所以这门语言非常流行。但若想掌握Python所特有的优势、魅力和表达能力，则相当困难，而且语言中还有很多隐藏的陷阱，容易令开发者犯错。\\n本书可以帮你掌握真正的Pythonic编程方式，令你能够完全发挥出Python语言的强大功能，并写出健壮而高效的代码。Scott Meyers在畅销书《Effective C++》中开创了一种以使用场景为主导的精练教学方式，本书作者Brett Slatkin就以这种方式汇聚了59条优秀的实践原则、开发技巧和便捷方案，并以实用的代码范例来解释它们。\\nSlatkin根据自己在Google公司多年开发Python基础架构所积累的经验，揭示Python语言中一些鲜为人知的微妙特性，并给出了能够改善代码功能及运行效率的习惯用法。通过本书，你能够了解到解决关键编程任务所用的最佳方式，并学会编写易于理解、便于维护且利于改进的代码。\\n本书核心内容包括：\\n涵盖Python 3.x及Python 2.x主要应用领域的实用指南，以及与之配套的详细解释及代码范例。\\n与函数相关的编程建议，这些建议有助于我们写出意图清晰、便于复用且缺陷较少的函数。\\n如何准确地表达类与对象的行为。\\n在使用元类和动态属性时，如何避免错误的用法。\\n更为高效的并发及并行方式。\\n与Python内置模块相关的编程技巧和习惯用法。\\n多人协作时所用的开发工具和最佳实践方式。\\n旨在改善代码质量和程序性能的调试、测试与优化方案。', 'https://img3.doubanio.com/lpic/s28384052.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 24, 'Flask Web开发：基于Python的Web应用开发实战', '[美] Miguel Grinberg', '平装', '人民邮电出版社', '59.00元', 224, '9787115373991', '本书不仅适合初级Web开发人员学习阅读，更是Python程序员用来学习高级Web开发技术的优秀参考书。\\n•	学习Flask应用的基本结构，编写示例应用；\\n•	使用必备的组件，包括模板、数据库、Web表单和电子邮件支持；\\n•	使用包和模块构建可伸缩的大型应用；\\n•	实现用户认证、角色和个人资料；\\n•	在博客网站中重用模板、分页显示列表以及使用富文本；\\n•	使用基于Flask的REST式API，在智能手机、平板电脑和其他第三方客户端上实现可用功能；\\n•	学习运行单元测试以及提升性能；\\n•	将Web应用部署到生产服务器。', 'https://img3.doubanio.com/lpic/s27906700.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 25, 'Python网络数据采集', '[美]米切尔', '平装', '人民邮电出版社', 'CNY 59.00', 200, '9787115416292', '本书采用简洁强大的Python语言，介绍了网络数据采集，并为采集新式网络中的各种数据类型提供了全面的指导。第一部分重点介绍网络数据采集的基本原理：如何用Python从网络服务器请求信息，如何对服务器的响应进行基本处理，以及如何以自动化手段与网站进行交互。第二部分介绍如何用网络爬虫测试网站，自动化处理，以及如何通过更多的方式接入网络。', 'https://img1.doubanio.com/lpic/s29086659.jpg');
INSERT INTO `book` VALUES (1576678589, 1, 26, 'Python Web开发实战', '董伟明', '平装', '电子工业出版社', '105', 504, '9787121297335', '这本书涵盖了Web开发的方方面面，可以分为如下部分：\\n1. 使用最新的Flask 0.11进行Web开发，学习Jinja2、Flask-Script、Flask-Migrate、Flask-Security、Flask-Assets等8种常用扩展，帮助读者理解Flask 的 优秀设计（上下文、BluePrint等），最后利用Mako、Flask_mako、SQLAlchemy、Pillow等技术实现一个豆瓣一个真实的服务。\\n2. 阐述笔者对REST的理解，并提出一些设计API的注意事项，最后通过jQuery和fetch实现使用Ajax的例子，让读者了解如何让前后端通信。\\n3. 对Python应用服务器，Web服务器、缓存系统、键值对数据库等技术的选型和使用方法，最后演示大型网站架构及其重要组件的用意。\\n4. 使用Fabric、SaltStack、Ansible、Supervisor、Graphite等做系统管理，并演示一个通过最新的Sentry 8演示如何收集应用错误信息。\\n5. 测试和持续集成，最后使用最新的Buildbot 0.9实现一个Github项目的持续集成。\\n6. 深入RabbitMQ和Celery的原理和使用方法，最后分享笔者使用的进阶实践。\\n7. 服务化及豆瓣服务化实践。\\n8. 详细讲解豆瓣工程师都在用的DPark，包含安装、环境配置、使用和框架化分析uv&pv，接着将展示几个笔者实际工作中的数据报表需求，并讲解如何用Pandas做数据可视化。\\n9. 深入IPython和Jupyter Notebook这两个工具，并分享在豆瓣对应的实践。\\n10. 从获取Linux服务器的相关情况、性能测试、分析Python程序性能瓶颈三个方面展示对应的工具及使用方法。\\n11. 以抓取微信公众号文章为主线，分别使用多线程、多进程、Gevent、Future和asyncio这5种编程方式完成不同阶段的爬取任务，也深入地分析在它们之间如何选择。\\n12. Python进阶和Web项目经验。\\n封底推荐语\\n伟明把他个人多年 Web 开发的经验，以及豆瓣十年来数百名优秀工程师在 Web 开发上最佳实践的积累，凝聚在了《Python Web 开发实战》这本书里，多维度、全面地介绍了 Python Web 开发涉及的各种技术。我向所有有兴趣使用 Pytho', 'https://img1.doubanio.com/lpic/s28994368.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 27, '用Python写网络爬虫', '[澳]理查德 劳森', '平装', '人民邮电出版社', 'CNY 45.00', 157, '9787115431790', '作为一种便捷地收集网上信息并从中抽取出可用信息的方式，网络爬虫技术变得越来越有用。使用Python这样的简单编程语言，你可以使用少量编程技能就可以爬取复杂的网站。\\n《用Python写网络爬虫》作为使用Python来爬取网络数据的杰出指南，讲解了从静态页面爬取数据的方法以及使用缓存来管理服务器负载的方法。此外，本书还介绍了如何使用AJAX URL和Firebug扩展来爬取数据，以及有关爬取技术的更多真相，比如使用浏览器渲染、管理cookie、通过提交表单从受验证码保护的复杂网站中抽取数据等。本书使用Scrapy创建了一个高级网络爬虫，并对一些真实的网站进行了爬取。\\n《用Python写网络爬虫》介绍了如下内容：\\n通过跟踪链接来爬取网站；\\n使用lxml从页面中抽取数据；\\n构建线程爬虫来并行爬取页面；\\n将下载的内容进行缓存，以降低带宽消耗；\\n解析依赖于JavaScript的网站；\\n与表单和会话进行交互；\\n解决受保护页面的验证码问题；\\n对AJAX调用进行逆向工程；\\n使用Scrapy创建高级爬虫。\\n本书读者对象\\n本书是为想要构建可靠的数据爬取解决方案的开发人员写作的，本书假定读者具有一定的Python编程经验。当然，具备其他编程语言开发经验的读者也可以阅读本书，并理解书中涉及的概念和原理。', 'https://img1.doubanio.com/lpic/s29088958.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 28, 'Python标准库', 'Doug Hellmann', NULL, '机械工业出版社华章公司', '139.00元', 1040, '9787111378105', '本书由资深Python专家亲自执笔，Python语言的核心开发人员作序推荐，权威性毋庸置疑。\\n对于程序员而言，标准库与语言本身同样重要，它好比一个百宝箱，能为各种常见的任务提供完美的解决方案，所以本书是所有Python程序员都必备的工具书！本书以案例驱动的方式讲解了标准库中一百多个模块的使用方法（如何工作）和工作原理（为什么要这样工作），比标准库的官方文档更容易理解（一个简单的示例比一份手册文档更有帮助），为Python程序员熟练掌握和使用这些模块提供了绝佳指导。\\n全书一共19章，系统而全面地对Python标准库中的一百多个模块进行了生动的讲解。这些模块主要包括：文本处理工具模块、与数据结构相关的模块、与算法有关的模块、管理日期和时间值的模块、用于数学计算的模块、管理文件系统的模块、用于数据存储与交换的模块、用于数据压缩与归档的模块、用于加密的模块、与进程和线程相关的模块、与网络通信和Email相关的模块、构建模块、支持处理多种自然语言和文化设置的模块、开发工具模块、与运行时特性相关的模块，等等。', 'https://img3.doubanio.com/lpic/s10245980.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 29, 'Think Python', 'Allen B. Downey', 'Paperback', 'O\'Reilly Media', 'GBP 29.99', 300, '9781449330729', 'Think Python is an introduction to Python programming for students with no programming experience. It starts with the most basic concepts of programming, and is carefully designed to define all terms when they are first used and to develop each new concept in a logical progression. Larger pieces, like recursion and object-oriented programming are divided into a sequence of smaller steps and introduced over the course of several chapters.', 'https://img3.doubanio.com/lpic/s29586154.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 30, '编写高质量代码：改善Python程序的91个建议', '张颖、赖勇浩', '平装', '机械工业出版社', '59.00元', 272, '9787111467045', '在通往“Python技术殿堂”的路上，本书将为你编写健壮、优雅、高质量的Python代码提供切实帮助！内容全部由Python编码的最佳实践组成，从基本原则、惯用法、语法、库、设计模式、内部机制、开发工具和性能优化8个方面深入探讨了编写高质量Python代码的技巧与禁忌，一共总结出91条宝贵的建议。每条建议对应Python程序员可能会遇到的一个问题。本书不仅以建议的方式从正反两方面给出了被实践证明为十分优秀的解决方案或非常糟糕的解决方案，而且分析了问题产生的根源，会使人有一种醍醐灌顶的感觉，豁然开朗。\\n《编写高质量代码：改善Python程序的91个建议》针对每个问题所选择的应用场景都非常典型，给出的建议也都与实践紧密结合。书中的每一条建议都可能在你的下一行代码、下一个应用或下一个项目中显露锋芒。建议你将本书搁置在手边，随时查阅，相信这么做一定能使你的学习和开发工作事半功倍。', 'https://img3.doubanio.com/lpic/s27308066.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 31, 'python绝技：运用python成为顶级黑客', '[美] TJ O\'Connor', '平装', '电子工业出版社', '79.00元', 264, '9787121277139', 'Python 是一门常用的编程语言，它不仅上手容易，而且还拥有丰富的支持库。对经常需要针对自己所 处的特定场景编写专用工具的黑客、计算机犯罪调查人员、渗透测试师和安全工程师来说，Python 的这些 特点可以帮助他们又快又好地完成这一任务，以极少的代码量实现所需的功能。《Python绝技：运用Python成为顶级黑客》结合具体的场景和真 实的案例，详述了 Python 在渗透测试、电子取证、网络流量分析、无线安全、网站中信息的自动抓取、 病毒免杀等领域内所发挥的巨大作用。\\n《Python绝技：运用Python成为顶级黑客》适合计算机安全管理人员、计算机犯罪调查和电子取证人员、渗透测试人员，以及所有对计算机 安全感兴趣的爱好者阅读。同时也可供计算机、信息安全及相关专业的本/专科院校师生学习参考。', 'https://img1.doubanio.com/lpic/s28385338.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 32, 'Python编程实战', '[美] Mark Summerfield', '平裝', '机械工业出版社', '69.00元', 252, '9787111473947', '《python编程实战：运用设计模式、并发和程序库创建高质量程序》由python开发者社区知名技术专家mark summerfield亲笔撰写，全球资深python专家doug hellmann作序鼎力推荐，是python领域最有影响力的著作之一。书中通过大量实用的范例代码和三个完整的案例研究，全面而系统地讲解了如何运用设计模式来规划代码结构，如何通过并发与cython等技术提升代码执行速度，以及如何利用各种python程序库来快速开发具体的应用程序和游戏。\\n《python编程实战：运用设计模式、并发和程序库创建高质量程序》共8章：第1～3章分别介绍了python的几种设计模式(创建型设计模式、结构型设计模式和行为型设计模式)；第4章和第5章详细讲解了python的高级并发技术以及cython的用法；第6章具体介绍了python的高级网络编程；第7章阐释了如何用tkinter开发图形用户界面；第8章讲解了如何用opengl绘制3d图形。', 'https://img3.doubanio.com/lpic/s27397566.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 33, 'Python灰帽子', '[美] Justin Seitz', '平装', '电子工业出版社', '39.00元', 216, '9787121129018', '《Python灰帽子》是由知名安全机构Immunity Inc的资深黑帽Justin Seitz主笔撰写的一本关于编程语言Python如何被广泛应用于黑客与逆向工程领域的书籍。老牌黑客，同时也是Immunity Inc的创始人兼首席技术执行官（CTO）Dave Aitel为这本书担任了技术编辑一职。书中绝大部分篇幅着眼于黑客技术领域中的两大经久不衰的话题：逆向工程与漏洞挖掘，并向读者呈现了几乎每个逆向工程师或安全研究人员在日常工作中所面临的各种场景，其中包括：如何设计与构建自己的调试工具，如何自动化实现烦琐的逆向分析任务，如何设计与构建自己的fuzzing工具，如何利用fuzzing 测试来找出存在于软件产品中的安全漏洞，一些小技巧诸如钩子与注入技术的应用，以及对一些主流Python安全工具如PyDbg、 Immunity Debugger、Sulley、IDAPython、PyEmu等的深入介绍。作者借助于如今黑客社区中备受青睐的编程语言 Python引领读者构建出精悍的脚本程序来一一应对上述这些问题。出现在书中的相当一部分Python代码实例借鉴或直接来源于一些优秀的开源安全项目，诸如Pedram Amini的Paimei，由此读者可以领略到安全研究者们是如何将黑客艺术与工程技术优雅融合来解决那些棘手问题的。', 'https://img3.doubanio.com/lpic/s4676930.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 34, '可爱的Python', '哲思社区', '平装', '电子工业出版社', '55.00元', 484, '9787121085147', '本书的内容主要来自CPyUG社区的邮件列表，由Python的行者根据自身经验组织而成，是为从来没有听说过Python的其他语言程序员准备的一份实用的导学性质的书。笔者试图将优化后的学习体验，通过故事的方式传达给读者，同时也分享了蟒样（Pythonic式）的知识获取技巧，而且希望将最常用的代码和思路，通过作弊条（Cheat Sheet，提示表单）的形式分享给有初步基础的Python 用户，来帮助大家多快好省地完成功能。\\n本书期望成为学习使用Python的同好们的沟通话题，引发进一步的学习/应用/创造/推广，就是笔者的追求！因为Python语言本身是种非常灵活的动态脚本语言，同一个目标可以使用多种方式完成，笔者为了让拥有各种不同技术背景的读者可以快速无碍地理解，选择了一种实际上可能比较笨拙的方式来实现功能，聪明的读者一定可以看出来的，那么请会心一笑，因为您已经和我们心灵相通了！', 'https://img1.doubanio.com/lpic/s3901817.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 35, 'Python高级编程', 'Tarek Ziadé', '平装', '人民邮电出版社', '45.00元', 306, '9787115217035', '《Python高级编程》通过大量的实例，介绍了Python语言的最佳实践和敏捷开发方法，并涉及整个软件生命周期的高级主题，诸如持续集成、版本控制系统、包的发行和分发、开发模式、文档编写等。《Python高级编程》首先介绍如何设置最优的开发环境，然后以Python敏捷开发方法为线索，阐述如何将已被验证的面向对象原则应用到设计中。这些内容为开发人员和项目管理人员提供了整个软件工程中的许多高级概念以及专家级的建议，其中有些内容的意义甚至超出了Python语言本身。\\n《Python高级编程》针对具备一定Python基础并希望通过在项目中应用最佳实践和新的开发技术来提升自己的Python开发人员。', 'https://img3.doubanio.com/lpic/s4163751.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 36, '趣学Python编程', 'Jason Briggs', '平装', '人民邮电出版社', '45.00元', 268, '9787115335951', 'python是一款解释型、面向对象、动态数据类型的高级程序设计语言。python语法简捷而清晰，具有丰富和强大的类库，因而在各种行业中得到广泛的应用。对于初学者来讲，python是一款既容易学又相当有用的编程语言，国内外很多大学开设这款语言课程，将python作为一门编程语言学习。\\n《趣学python编程》是一本轻松、快速掌握python编程的入门读物。全书分为3部分，共18章。第1部分是第1章到第12章，介绍python编程基础知识，包括python的安装和配置、变量、字符串、列表、元组和字典、条件语句、循环语句函数和模块、类、内建函数和绘图，等等。第2部分是第13章和第14章，介绍如何用python开发实例游戏弹球。第3部分包括第15章到第18章，介绍了火柴人实例游戏的开发过程。\\n《趣学python编程》语言轻松，通俗易懂，讲解由浅入深，力求将读者阅读和学习的难度降到最低。任何对计算机编程有兴趣的人或者首次接触编程的人，不论孩子还是成人，都可以通过阅读本书来学习python编程。', 'https://img3.doubanio.com/lpic/s27228664.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 37, 'Python网络编程基础', 'John Goerzen', '平装', '电子工业出版社', '68.00元', 512, '9787121044953', '《Python网络编程基础》可以作为各层次Python、Web和网络程序的开发人员的参考书，在实际工作中使用书中的技术，效果更佳。', 'https://img3.doubanio.com/lpic/s2604186.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 38, 'Python Tutorial', 'Guido Van Rossum、Fred L. Drake, Jr (editor)', 'Paperback', 'Iuniverse Inc', 'USD 12.95', 140, '9781583483756', '最权威的 Python 教程，由 Python 作者 Guido van Rossum 主笔，有少许学院味道。中文电子版由刘鑫、李梦夷翻译。英文原稿网址：http://docs.python.org/tut/简体中文版网址：http://wiki.woodpecker.org.cn/moin/March_Liu/PyTutorial', 'https://img3.doubanio.com/lpic/s4251645.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 39, 'Python 3面向对象编程', '[加]Dusty Phillips（达斯帝•菲利普斯）', '平装', '电子工业出版社', '79.00元', 380, '9787121262463', 'Python 是一种面向对象的解释型语言，面向对象是其非常重要的特性。《Python 3面向对象编程》通过Python 的数据结构、语法、设计模式，从简单到复杂，从初级到高级，一步步通过例子来展示了Python 中面向对象的概念和原则。\\n《Python 3面向对象编程》不是Python 的入门书籍，适合具有Python 基础经验的开发人员阅读。如果你拥有其他面向对象语言的经验，你会更容易理解《Python 3面向对象编程》的内容。', 'https://img1.doubanio.com/lpic/s28153549.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 40, 'High Performance Python', 'Micha Gorelick、Ian Ozsvald', 'Paperback', 'O\'Reilly Media', 'USD 39.99', 380, '9781449361594', 'If you\'re an experienced Python programmer, High Performance Python will guide you through the various routes of code optimization. You\'ll learn how to use smarter algorithms and leverage peripheral technologies, such as numpy, cython, cpython, and various multi-threaded and multi-node strategies. There\'s a lack of good learning and reference material available if you want to learn Python for highly computational tasks. Because of it, fields from physics to biology and systems infrastructure to data science are hitting barriers. They need the fast prototyping nature of Python, but too few people know how to wield it. This book will put you ahead of the curve.', 'https://img3.doubanio.com/lpic/s28265052.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 41, '数据结构与算法：Python语言描述', '裘宗燕', '平装', '机械工业出版社', 'CNY 45.00', 343, '9787111521181', '本书基于Python语言介绍了数据结构与算法的基本知识，主要内容包括抽象数据类型和Python面向对象程序设计、线性表、字符串、栈和队列、二叉树和树、集合、排序以及算法的基本知识。本书延续问题求解的思路，从解决问题的目标来组织教学内容，注重理论与实践的并用。', 'https://img3.doubanio.com/lpic/s28388882.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 42, 'Python入门经典', '(美)William F. Punch/Richard Enbody', '平装', '机械工业出版社', '79.00元', 452, '9787111394136', '《Python入门经典:以解决计算问题为导向的Python编程实践》是一本系统而科学的Python入门教程，美国密歇根州立大学等多所美国知名高校采用其作为编程语言的入门教材，被奉为经典。它不仅从计算机教学和计算机科学的角度讲解了初学者如何才能更有效地去学习Python，而且特别强调用Python解决生活中的实际问题，精心组织了大量来源于生活中不同领域的与数值计算和数据处理相关的案例。通过《Python入门经典:以解决计算问题为导向的Python编程实践》，读者不仅能系统掌握Python编程相关的知识，而且还能掌握利用Python处理各种与数据相关的问题。《Python入门经典:以解决计算问题为导向的Python编程实践》分为五部分，第一部分介绍计算机设备的一般概念和一些计算机术语；第二部分开始介绍编程的基本知识，包括入门知识和控制语句，为后续内容做铺垫；第三部分讲述数据结构和函数，包括字符串、列表和元组、字典和集合、文件、函数、算法和程序等进阶内容，有助于读者提升编程技能；第四部分重点介绍如何使用类定义数据结构和算法、开发程序等，培养读者运用Python语言来实现基本的计算思想和策略的能力；第五部分主要介绍异常、测试和递归，旨在使读者成为更好的程序员。《Python入门经典:以解决计算问题为导向的Python编程实践》深入浅出，每一章节均给出了大量的实例、示范代码和自测练习，便于读者理解和掌握相关知识。读者通过学习《Python入门经典:以解决计算问题为导向的Python编程实践》，不仅能掌握Python语言的基本知识，还能学习如何在实践中运用该语言解决问题。', 'https://img3.doubanio.com/lpic/s11430346.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 43, 'Python金融大数据分析', '[德] 伊夫·希尔皮斯科', '平装', '人民邮电出版社', 'CNY 99.00', 511, '9787115404459', '唯一一本详细讲解使用Python分析处理金融大数据的专业图书；金融应用开发领域从业人员必读。\\nPython凭借其简单、易读、可扩展性以及拥有巨大而活跃的科学计算社区，在需要分析、处理大量数据的金融行业得到了广泛而迅速的应用，并且成为该行业开发核心应用的首选编程语言。《Python金融大数据分析》提供了使用Python进行数据分析，以及开发相关应用程序的技巧和工具。\\n《Python金融大数据分析》总计分为3部分，共19章，第1部分介绍了Python在金融学中的应用，其内容涵盖了Python用于金融行业的原因、Python的基础架构和工具，以及Python在计量金融学中的一些具体入门实例；第2部分介绍了金融分析和应用程序开发中最重要的Python库、技术和方法，其内容涵盖了Python的数据类型和结构、用matplotlib进行数据可视化、金融时间序列数据处理、高性能输入/输出操作、高性能的Python技术和库、金融学中需要的多种数学工具、随机数生成和随机过程模拟、Python统计学应用、Python和Excel的集成、Python面向对象编程和GUI的开发、Python与Web技术的集成，以及基于Web应用和Web服务的开发；第3部分关注的是蒙特卡洛模拟期权与衍生品定价实际应用的开发工作，其内容涵盖了估值框架的介绍、金融模型的模拟、衍生品的估值、投资组合的估值、波动率期权等知识。\\n《Python金融大数据分析》适合对使用Python进行大数据分析、处理感兴趣的金融行业开发人员阅读。', 'https://img3.doubanio.com/lpic/s28358933.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 44, 'Python计算机视觉编程', '[瑞典] Jan Erik Solem', '平装', '人民邮电出版社', '69.00', 284, '9787115352323', '《python计算机视觉编程》是计算机视觉编程的权威实践指南，依赖python语言讲解了基础理论与算法，并通过大量示例细致分析了对象识别、基于内容的图像搜索、光学字符识别、光流法、跟踪、三维重建、立体成像、增强现实、姿态估计、全景创建、图像分割、降噪、图像分组等技术。另外，书中附带的练习还能让读者巩固并学会应用编程知识。\\n《python计算机视觉编程》适合的读者是：有一定编程与数学基础，想要了解计算机视觉的基本理论与算法的学生，以及计算机科学、信号处理、物理学、应用数学和统计学、神经生理学、认知科学等领域的研究人员和从业者。', 'https://img3.doubanio.com/lpic/s27305520.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 45, 'Python参考手册（第4版）', 'David M.Beazley', '平装', '人民邮电出版社', '89.00元', 540, '9787115242594', '本书是权威的Python语言参考指南，内容涉及核心Python语言和Python库的最重要部分。本书内容简洁扼要、可读性强，书中还包括了一些没有在Python官方文档或其他资料中出现过的一些高级的主题。\\n这一版在内容上进行了全面更新，介绍了Python 2.6和Python 3新引入的编程语言特性和库模块，同时还分析了Python程序员面临的如下难题：是应继续使用现有的Python代码，还是应制定计划将其移植到Python 3？', 'https://img3.doubanio.com/lpic/s4568752.jpg');
INSERT INTO `book` VALUES (1576678616, 1, 46, 'Python数据可视化编程实战', 'Igor Milovanovic', '平装', '人民邮电出版社', '49.00元', 242, '9787115384393', '《Python数据可视化编程实战》是一本使用Python实现数据可视化编程的实战指南，介绍了如何使用Python最流行的库，通过60余种方法创建美观的数据可视化效果。\\n全书共8章，分别介绍了准备工作环境、了解数据、绘制并定制化图表、学习更多图表和定制化、创建3D可视化图表、用图像和地图绘制图表、使用正确的图表理解数据以及更多matplotlib知识。\\n《Python数据可视化编程实战》适合那些对Python编程有一定基础的开发人员，可以帮助读者从头开始了解数据、数据格式、数据可视化，并学会使用Python可视化数据。', 'https://img3.doubanio.com/lpic/s28060713.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 47, 'Linux命令行与shell脚本编程大全', 'Richard Blum、Christine Bresnahan', '平装', '人民邮电出版社', '99.00元', 619, '9787115288899', '本书是一本关于Linux 命令行与shell 脚本编程的全面教程。全书分为四部分：第一部分介绍Linuxshell 命令行；第二部分介绍shell 脚本编程基础；第三部分深入探讨shell 脚本编程的高级内容；第四部分介绍如何在现实环境中使用shell 脚本。本书不仅涵盖了详尽的动手教程和现实世界中的实用信息，还提供了与所学内容相关的参考信息和背景资料。\\n本书内容全面，语言简练，示例丰富，适合于Linux 系统管理员及Linux 爱好者阅读参考。', 'https://img3.doubanio.com/lpic/s11171426.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 48, 'Linux Shell脚本攻略', '(印)拉克什曼', '平装', '人民邮电出版社', '49.00元', 254, '9787115264725', '《Linux Shell脚本攻略》通过细致剖析实际应用中的110多个案例，使许多看似复杂的Linux shell脚本任务迎刃而解。《Linux Shell脚本攻略》会帮助读者利用少量命令的组合完成诸如文本处理、文件管理、备份等复杂的数据管理工作。它将告诉你如何利用shell命令快速开发常规任务，综合应用grep、find、sed和awk等常用命令，凭借短短几个命令行从Web挖掘数据的shell脚本，利用归档工具运行并自动化各种任务，诸如自动备份和存储；帮助你理解文件系统、文件类型以及文件管理；用shell创建以及维护文件或目录归档、压缩格式和加密技术；通过srlell脚本设置以太网和无线LAN；使用登录技术监控网络上的各种动态。', 'https://img1.doubanio.com/lpic/s22702207.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 49, 'Shell脚本学习指南', 'Arnold Robbins、Nelson H.F.Beebe', NULL, '机械工业出版社', '79.00元', 494, '9787111255048', '《Shell脚本学习指南》将告诉你这些有关UNIX主流工具的知识。除此之外，《Shell脚本学习指南》还会帮助你解决UNIX命令与标准的差异。\\n作者熟知UNIx程序使用的基本技巧与操作上细微的差异。他们不但会告诉你如何构建一个绝佳的脚本，还会教你如何避免落入让你功亏一篑的陷阱。有了《Shell脚本学习指南》，你可以节省很多力气。\\n我们要学习的不只是如何写出有用的Shell脚本，你还得了解如何迅速、确实地定制Shell，让程序的可移植性达到最佳状态，脱离对特定系统的依赖。这些技巧对任何操作与维护UNIX及Linux系统的人而言都很重要。《Shell脚本学习指南》所提供的知识，将可以帮助你掌握基本的Shell脚本编写技巧。Shell脚本编程(scripting)的技巧永远不会过时：它们可以让UNIX充分发挥其真实的潜能。对uNIx的用户与系统管理者而言，编写shell脚本是必须的工作，它可以让你快速地控制与定制任何UNIX系统的强大功能。有了Shell脚本，你可以结合基本的UNIX文本与文件处理命令来消化数据，以及自动化重复的工作。一旦你对Shell脚本的编写掌控自如，在接下来的几年，这些技巧将对你相当有帮助。\\n编写shell脚本所需要的不只是对shell语言的认识，还必须熟知单个的uNIx程序：你必须知道每个程序为什么会放在那儿，以及如何使用该程序或如何将其与其他程序结合。', 'https://img1.doubanio.com/lpic/s3801638.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 50, '算法技术手册', 'George T. Heineman、Gary Pollice、Stanley Selkow', '平装', '机械工业出版社', '55.00元', 333, '9787111286745', '《算法技术手册》内容简介：开发健壮的软件需要高效的算法，然后程序员们往往直至问题发生之时，才会去求助于算法。《算法技术手册》讲解了许多现有的算法，可用于解决各种问题。通过阅读它，可以使您学会如何选择和实现正确的算法，来达成自己的目标。另外，书中的数学深浅适中，足够使您可以了解并分析算法的性能。\\n较之理论而言，《算法技术手册》更专注于应用。《算法技术手册》提供了高效的代码解决方案，使用多种语言进行编写，让您可以轻松地将其应用于特定的工程当中。通过《算法技术手册》，您可以：\\n· 解决特定代码的问题，或者提升既有解决方案的性能\\n· 快速找到与您所解决的问题相关的算法，并决定哪个算法才是最适合的那一个\\n· 探索使用C、C++、Java以及Ruby实现的算法解决方案以及开发小贴士\\n· 了解算法预期的性能，以及它达到最高性能时所需要的条件\\n· 发现不同算法之间相似的设计哲学\\n· 学习高级数据结构，来提升算法的性能\\n通过《算法技术手册》，您能学到如何提升算法的性能，这将是您的软件应用程序走向成功的关键。', 'https://img1.doubanio.com/lpic/s6144917.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 51, '黑客攻防技术宝典', 'Chris Anley、John Heasman、Felix Linder、Gerardo Richarte', '平装', '人民邮电出版社', '79.00元', 545, '9787115217967', '《黑客攻防技术宝典:系统实战篇(第2版)》由世界顶级安全专家亲自执笔，详细阐述了系统安全、应用程序安全、软件破解、加密解密等安全领域的核心问题，并用大量的实例说明如何检查Windows、Linux、Solaris等流行操作系统中的安全漏洞和Oracle等数据库中的安全隐患。\\n《黑客攻防技术宝典:系统实战篇(第2版)》适用于所有计算机安全领域的技术人员和管理人员以及对计算机安全感兴趣的爱好者。', 'https://img3.doubanio.com/lpic/s6779762.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 52, 'Linux命令、编辑器与Shell编程', 'Mark G. Sobell', '平装', '清华大学出版社', '98.00元', 792, '9787302139447', '1. 它是Pearson、Amazon、Bames&Noble 计算机畅销书！\\n2. 知名Linux专家Mark Sobell 编写的这本书，为系统管理员、开发人员和高级用户提供了最需要的全面的深入指导，同时还是一本卓越的日常参考手册。\\n3. 一本值得每一位Linux管理人员、开发人员和高级用户拥有的指南！\\n4. 本书并不针对特定的Linux版本或者某个发行版本，而是适用于所有近期发布的Linux版本;\\n5. 最实用的Linux指南和参考手册，数百个高质量的实例覆盖了每种Linux发行版！\\n6. 本书覆盖超过80个核心工具、shell编程、编辑器和编程工具，能使您成为真正的Linux高手，它是掌握强大的Linux命令行的捷径。', 'https://img1.doubanio.com/lpic/s2338599.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 53, '精通shell编程', '韦拉拉格温(Veeraraghavan Sriranga)', '平装', '人民邮电出版社', '39.0', 350, '9787115111418', '本书由浅入深地介绍了shell编程技术。为了满足不同读者的需要，本书内容分为三个部分：UNIX和shell工具介绍、shell编程以及高级主题。UNIX和shell工具介绍部分复习了UNIX系统和shell编程的一些基本概念和常用命令。shell编程部分全面介 绍了shell编程的每个技术环节。最后，高级主题部分讲解了一些比较有难度的专题。本书既可以作为学习教材，又可以作为参考手册。通过阅读本书，读者可以全面掌握shell编程的知识。\\n本书适合任何对shell编程感兴趣的读者。初级读者可以从本书第一部分获得入门知识，中、高级读者可以越过第一部分，直接从第二部分和第三部分深入了解有关shell编程的知识。', 'https://img1.doubanio.com/lpic/s3123987.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 54, 'LINUX与UNIX Shell编程指南', '[美] （D.坦思', NULL, '机械工业出版社', '38.00元', 357, '9787111080411', '本书共分五部分，详细介绍了shell编程技巧，各种UNIX命令及语法，还涉及了UNIX下的文字处理以及少量的系统管理问题。本书内容全面、文字简洁流畅，适合Shell编程人员学习、参考。', 'https://img1.doubanio.com/lpic/s1410857.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 55, 'Learn Windows PowerShell in a Month of Lunches', 'Don Jones、Jeffery Hicks', 'Paperback', 'Manning Publications', 'USD 44.99', 368, '9781617291081', 'PowerShell provides a single, unified administrative command line  from which to control and automate virtually every aspect of a  Windows system. It accepts and executes commands immediately, and  scripts can be written to manage most Windows servers like Exchange,  IIS, and SharePoint. PowerShell 3 adds features designed specifically  for Windows Server 2012 and even third-party platforms from  companies like Citrix and VMware. Learn Windows PowerShell 3 in a Month of Lunches, Second Edition is an innovative tutorial designed for administrators. With just one hour a  day, readers will be automating Windows tasks faster than ever thought  possible. The book starts with the basics-what is PowerShell and  what can be done with it. Then, it moves systematically through the  techniques and features that facilitate efficient and effective results. AUDIENCE  The book is written for administrators, not developers. No prior  PowerShell experience or any scripting or programming experience is ', 'https://img1.doubanio.com/lpic/s29549719.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 56, 'C# 5.0 in a Nutshell', 'Joseph Albahari、Ben Albahari', 'Paperback', 'O\'Reilly Media', 'GBP 38.50', 1064, '9781449320102', 'When you have a question about how to use C# 5.0 or the .NET CLR, this highly acclaimed bestseller has precisely the answers you need. Uniquely organized around concepts and use cases, this fifth edition include in-depth cover of concurrency and asynchrony new to C# 5.0 as well as continued coverage of parallel programming, code contracts, dynamic programming, security and COM interoperability. You\'ll also find updated information on language enhancements such as Caller Info Attributes, ReadOnlyDictionary, Web Sockets, and the new HttpClient class. This handy book has all you need to stay on track with C# 5.0. Get up to speed on C# language basics, including syntax, types, and variables Explore advanced topics such as unsafe code and preprocessor directives Learn C# 5.0 features such as concurrency and asynchrony Work with .NET 4.5\'s rich set of features for parallel programming, code contracts, and the code security model Understand .NET topics, including XML, collections, I/O and net', 'https://img3.doubanio.com/lpic/s11325223.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 57, '学习bash', 'Cameron Newham、Bill Rosenblatt', '平装', '机械工业出版社', '45.00', 356, '9787111107231', 'bash是自由软件基金会发布的“Bourne Again Shell”的缩写。它是流行的UNIX Bourne shell的免费可用替代产品，供全球Linux用户选用。《学习bash》正是bash的权威指南。\\n无论你是对bash的用户界面感兴趣，还是对其强大的编程能力感兴趣，你都会发现本书很有价值。它教授了如何使用bash的高级命令行特性，如命令历史、命令行编辑和命令完成。\\n本书还介绍了shell编程，一种UNIX或Linux用户不可或缺的技巧，阐述了如何使用bash的编程特性完成各种功能。读者还将学习流程控制、信号处理以及命令行处理和I／O方面的内容以及如何调试bash程序。\\n最后，本书介绍了如何获取、安装、配置和定制bash，并为系统管理员提供了如何对其用户群体进行bash管理的建议。第二版包括了bash 2．0版本的所有特性，同时也适用于bash1．x版本。bash的新特性包括一维数组、参数扩展和更多的模式匹配操作。bash 2．0甚至提供了与POSIX．2标准更多的一致性，并且在POSIX．2模式中，它是完全与POSIX．2一致的。\\n第二版还加入了一些新命令，增强了安全性，也加入了readline，增强了配置和安装过程，并且增加了附助编程的bash shell调试器。 经过不懈的实践和对实例及问题进行深入的研究后，你会发现《学习bash》对Linux和其他UNIX用户来说是很有价值的。', 'https://img1.doubanio.com/lpic/s24430749.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 58, 'JavaScript经典实例', 'Shelley Powers', NULL, '中国电力出版社', '78.00元', 512, '9787512320581', '《JavaScript经典实例》各节中的完整代码解决了常见的编程问题，并且给出了在任何浏览器中构建Web应用程序的技术。只需要将这些代码示例复制并粘贴到你自己的项目中就行了，可以快速完成工作，并且在此过程中学习JavaScript的很多知识。你还将学习如何利用ECMAScript5和HTML5中的最新功能，包括新的跨域挂件通信技术、HTML5的video和audio元素，以及绘制画布。《JavaScript经典实例》中一些章节介绍了如何将这些技术与JavaScript一起使用，构建高品质的应用程序界面。', 'https://img3.doubanio.com/lpic/s24977623.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 59, 'JavaScript核心技术', 'Shelley Powers', '平装', '机械工业出版社', '45.00', 340, '9787111212973', 'Ajax是当今Web开发领域最流行的词汇。而JavaScript与CSS、XML和DOM几种老技术，加上XMLHttpRequest就构成了Ajax的四大基石。对于JavaScript，一些更资深的同事告诉我的感觉是失望。面对不同的浏览器和浏览器的不同版本，没有优秀的调试开发工具，JavaScript成了软件开发的泥潭。.\\n而本书的出版则给我们增加了一丝解决这些问题的信心。\\n它从最简单的地方入手，不仅讲述了JavaScript的基础知识，还讲述了JavsScript如何操作CSS、DOM等Ajax基础技术。而关于跨浏览器兼容问题的解决，则贯穿了本书的始终。本书对于各种浏览器、浏览器版本、JavaScript版本、DOM版本的介绍，有助于我们理解所遇到的各种新旧代码，使我们能够对这些代码做出正确的取舍。..\\n本书还提供了一些使用JavaScript的最佳实践。无论是新手还是老手，这些如何正确使用JavaScript的经验都能帮助他们养成良好的编程习惯。本书还介绍了一些调试和开发JavaScript的工具，这些工具无疑能够提高我们的开发效率。\\n本书最后对于Ajax和几个流行的JavaScript库的介绍，无疑会开阔我们在JavaScript使用上的思路。\\n本书是一本真正意义上的“新书”，不仅介绍了最新的JavaScript知识和方向，还完全覆盖了当今Web开发中关于JavaScript的所有重要话题，它使用了大量实例代码，图文并茂地讲解了使用JavaScript的各个层次和领域的内容。它不是一本参考手册，但却是一本值得拥有的教程。...', 'https://img1.doubanio.com/lpic/s2619079.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 60, 'Painting the Web', 'Shelley Powers', 'Paperback', 'O\'Reilly Media, Inc.', 'USD 44.99', 400, '9780596515096', 'Painting the Web is the first comprehensive book on web graphics to come along in years, and author Shelley Powers demonstrates how readers of any level can take advantage of the graphics and animations capabilities built into today\'s powerful browsers. She covers GIFs and JPEGs, raster images, vector graphics, SVG, CSS, Ajax effects, canvas objects, geographical applications, and more -- everything that designers (and non-designers) use to literally paint the Web.', 'https://img1.doubanio.com/lpic/s3057519.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 61, 'Practical RDF', 'Shelley Powers', 'Paperback', 'O\'Reilly Media, Inc.', 'USD 39.95', 352, '9780596002633', 'The Resource Description Framework (RDF) is a structure for describing and interchanging metadata on the Web--anything from library catalogs and worldwide directories to bioinformatics, Mozilla internal data structures, and knowledge bases for artificial intelligence projects. RDF provides a consistent framework and syntax for describing and querying data, making it possible to share website descriptions more easily. RDF\'s capabilities, however, have long been shrouded by its reputation for complexity and a difficult family of specifications. Practical RDF breaks through this reputation with immediate and solvable problems to help you understand, master, and implement RDF solutions.    Practical RDF explains RDF from the ground up, providing real-world examples and descriptions of how the technology is being used in applications like Mozilla, FOAF, and Chandler, as well as infrastructure you can use to build your own applications. This book cuts to the heart of the W3C\'s often obscure ', 'https://img3.doubanio.com/lpic/s1478423.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 62, 'Web Design in a Nutshell', 'Jennifer Niederst Robbins', 'Paperback', 'O\'Reilly Media', 'USD 34.99', 704, '9781600330124', '', 'https://img1.doubanio.com/lpic/s4181428.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 63, 'Rapid Contextual Design', 'Karen Holtzblatt、Jessamyn Burns Wendell、Shelley Wood', 'Paperback', 'Morgan Kaufmann', 'USD 59.95', 320, '9780123540515', '在线阅读本书\\nIs it impossible to schedule enough time to include users in your design process? Is it difficult to incorporate elaborate user-centered design techniques into your own standard design practices? Do the resources needed seem overwhelming?   This handbook introduces Rapid CD, a fast-paced, adaptive form of Contextual Design. Rapid CD is a hands-on guide for anyone who needs practical guidance on how to use the Contextual Design process and adapt it to tactical projects with tight timelines and resources.   Rapid Contextual Design provides detailed suggestions on structuring the project and customer interviews, conducting interviews, and running interpretation sessions. The handbook walks you step-by-step through organizing the data so you can see your key issues, along with visioning new solutions, storyboarding to work out the details, and paper prototype interviewing to iterate the design-all with as little as a two-person team with only a few weeks to spare!\\n*Includes real p', 'https://img3.doubanio.com/lpic/s4356100.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 64, 'R in a Nutshell', 'Joseph Adler', 'Paperback', 'O\'Reilly Media', 'GBP 38.50', 640, '9780596801700', 'R is rapidly becoming the standard for developing statistical software, and R in a Nutshell provides a quick and practical way to learn this increasingly popular open source language and environment. You\'ll not only learn how to program in R, but also how to find the right user-contributed R packages for statistical modeling, visualization, and bioinformatics.', 'https://img1.doubanio.com/lpic/s7041788.jpg');
INSERT INTO `book` VALUES (1576678656, 1, 65, 'Group Theory in a Nutshell for Physicists', '徐一鸿', 'Hardcover', 'Princeton University Press', 'USD 90.00', 584, '9780691162690', 'Although group theory is a mathematical subject, it is indispensable to many areas of modern theoretical physics, from atomic physics to condensed matter physics, particle physics to string theory. In particular, it is essential for an understanding of the fundamental forces. Yet until now, what has been missing is a modern, accessible, and self-contained textbook on the subject written especially for physicists.\\nGroup Theory in a Nutshell for Physicists fills this gap, providing a user-friendly and classroom-tested text that focuses on those aspects of group theory physicists most need to know. From the basic intuitive notion of a group, A. Zee takes readers all the way up to how theories based on gauge groups could unify three of the four fundamental forces. He also includes a concise review of the linear algebra needed for group theory, making the book ideal for self-study.\\nProvides physicists with a modern and accessible introduction to group theory\\nCovers applications to variou', 'https://img1.doubanio.com/lpic/s28570309.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 66, '天龙八部', '金庸', '平装', '三联书店', '96.0', 1573, '9787108006721', '天龙八部乃金笔下的一部长篇小说，与《射雕》，《神雕》等    几部长篇小说一起被称为可读性最高的金庸小说。《天龙》的故事情节曲折，内容丰富，也曾多次被改编为电视作品。是金庸作品中集大成的一部。故事以南宋末年动荡的社会环境为背景，展开波澜壮阔的历史画卷，塑造了乔峰、段誉、虚竹、慕容复等形象鲜明的人物，成为武侠史上的经典之作。故事精彩纷呈，人物命运悲壮多变，是可读性很强的作品，具有震撼人心的力量', 'https://img1.doubanio.com/lpic/s23632058.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 67, '笑傲江湖（全四册）', '金庸', '平装', '生活·读书·新知三联书店', '76.80元', 1599, '9787108006639', '《笑傲江湖》是金庸1967年写的一部武侠小说，属于金庸的后期作品。', 'https://img3.doubanio.com/lpic/s2157335.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 68, '神雕侠侣', '金庸', '平装', '生活·读书·新知三联书店', '76.8', 1564, '9787108006660', '《神雕侠侣》是金庸作品集之一。其主人公杨过自然而然地走上了非正统的人生道路，入了“道流”。其特点是“至情至性，实现自我”，即把个人的利益、情感、个性及人格尊严置于人生首位，作为首要目标，亦作为待人处事，评价是非的首要原则。书中将杨过对郭靖的杀父之仇与疼惜之恩难以取舍的复杂心理刻画得维妙维肖；他与“姑姑”小龙女的情感纠葛和他对江湖世事的渴望又令他挣扎不已……', 'https://img3.doubanio.com/lpic/s26018916.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 69, '射雕英雄传（全四册）', '金庸', '平装', '生活·读书·新知三联书店', '47.00元', 1263, '9787108012586', '《射雕英雄传》是金庸的代表作之一，作于一九五七年到一九五九年，在《香港商报》连载。《射雕》中的人物个性单纯，郭靖诚朴厚重、黄蓉机智狡狯，读者容易印象深刻。这是中国传统小说和戏剧的特征，但不免缺乏人物内心世界的复杂性。由于人物性格单纯而情节热闹，所以《射雕》比较得到欢迎，被拍成各种语种的电影和电视剧在全球众多国家和地区热播。', 'https://img3.doubanio.com/lpic/s2157336.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 70, '金庸全集', '金庸', '精装', '生活·读书·新知三联书店', NULL, NULL, '9787845410256', '', 'https://img1.doubanio.com/lpic/s28345048.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 71, '鹿鼎记（全五册）', '金庸', '平装', '广州出版社 花城出版社', '108.00元', 1821, '9787806553404', '《鹿鼎记》是金庸创作的最后一部小说，也是他最重要的代表作。\\n小说讲的是一个从小在扬州妓院长大的小孩韦小宝，他以不会任何武功之姿态闯江湖各大帮会、周旋皇帝朝臣之间并奉旨远征云南、俄罗斯之故事，书中充满精彩的对白及逆思考的事件。\\n韦小宝笑称自己“不学无术却处处有术”，他靠着这不学之术在太监、钦命大臣、帮会堂主、和尚、甚至七个美女的共同老公这些角色上游刃有余。这个人物挑战了真实的人性，说明武功和权力不是这世上唯一的可取之道。', 'https://img3.doubanio.com/lpic/s3134040.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 72, '倚天屠龙记(共四册)', '金庸', '平装', '三联书店', '0', 1335, '9787108012692', '《倚天屠龙记》，金庸武侠小说，著于1961年，是“射雕三部曲”系列第三部，现收录在《金庸作品集》中。该书以元末群雄纷起、江湖动荡为广阔背景，叙述武当弟子张无忌的江湖生涯，表现众武林豪杰质朴自然，形态各异的精神风貌，展现其不可替代的人格力量。', 'https://img1.doubanio.com/lpic/s1829709.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 73, '金庸作品集', '金庸', NULL, '广州出版社', '683', NULL, '9787070511209', '', 'https://img3.doubanio.com/lpic/s2834105.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 74, '金庸散文集', '金庸', '平装', '作家出版社', '35.00元', 393, '9787506337496', '金庸先生撰著的汇集其60多年间散文精华的《金庸散文集》，日前由作家出版社推出。该书是中国内地惟一一本得到金庸先生授权正式出版的散文作品集，收录了金庸从上世纪５０年代以来在报纸杂志散落发表的近百篇文章，多数是金庸对电影、话剧、戏曲、歌舞等各门艺术的鉴赏文字，还有历史随笔、游记及武侠小说的创作心得等，全书４０余万字。这些文字呈现了金庸先生广泛的兴趣和游历，其中值得一提的是金庸关于莎士比亚话剧和经典外国电影、中国传统戏曲的点评文章，非常有功力。', 'https://img3.doubanio.com/lpic/s1877024.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 75, '再看金庸小说', '倪匡', '平装', '重庆大学出版社', '22.00元', 210, '9787562447252', '本书是倪匡对金庸作品《鹿鼎记》、《天龙八部》、《倚天屠龙记》的专题评论。依照“武侠小说=武+侠+小说”的观念，倪匡点评人物、随小说情节而笑而叹，浑然忘我，畅快淋漓，幽默而有余韵，并对金庸小说中的“武”做了评价。', 'https://img3.doubanio.com/lpic/s3443731.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 76, '我看金庸小说', '倪匡', '平装', '重庆大学出版社', '15.00元', 160, '9787562447245', '本书用风趣而睿智的笔调，信手拈来、娓娓讲述了金庸武侠小说的创作特点，并且依照作品的不同程度，对金庸作品一一点评，排位论次；按人格的高低优劣，对金庸小说中的主要人物“品头论足”，评定等级。读来情趣盎然，引人入胜。', 'https://img1.doubanio.com/lpic/s3443698.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 77, '白马啸西风', '金庸', NULL, '海口-南海出版社', NULL, NULL, '9787805702513', '吕梁三杰霍元龙、史仲俊、陈达海为抢夺一幅埋藏宝物的高昌迷宫图，带人与师妹上官虹及其夫白马李三交手。\\n由于寡不敌众，李三夫妇一直跑到回疆，仍没摆脱追踪，夫妻顽强抗战，手刃数名强敌，杀死史仲俊，双双战死。白马带着他们七岁的女儿李文秀跑入沙漠，遇见大风沙，吹至哈萨克人的居住区，被这里唯一的汉人叶老丈收养。霍元龙和陈达海找不到李文秀，对村中老弱病残妇的哈萨克人进行屠杀掠夺，引起哈萨克人的仇恨。李文秀自此后与叶老丈一同生活，并与哈萨克第一勇士苏鲁克的儿子苏普结为好友。\\n一次他们一同玩时遇见一头大狼，被二人合力杀死。苏鲁克因不在家时妻子被霍元龙等所害，从而仇恨所有的汉人，阻止苏普与李文秀来往；李文秀见苏普挨父亲的毒打，把他送给自己的狼皮送到哈萨克美丽的少女阿曼的门口，再也不见苏普。\\n随着时间的推移，李文秀变成了大姑娘，她偷偷观看苏普与人比武摔跤，却发现了阿曼对苏普的爱情，伤心而走，被一直在回疆寻找她的霍元龙手下之人发现。李文秀想起父母的仇恨，欲将他们带入戈壁之中，同归于尽，却巧遇隐藏在此的一指震江南华辉，在他的指导下，用毒针杀死围追的敌人，并帮助华辉挖出背上的毒针，拜他为师。两年时间，李文秀不时去华辉处学艺，已成为武林高手。\\n这日苏普与阿曼为避冰雪来到叶老丈家中，碰巧陈达海也来这里。一个询问儿时的伙伴，一个追查当年的汉族小姑娘，动起手来，苏普被陈达海所伤，李文秀此时女扮男装，打败陈达海，救出阿曼，还给苏昔。众人为追逃走的陈达海，来到迷宫，遇见躲在这里的华辉。他原是哈萨克人，本叫瓦耳拉齐，因在追求阿曼母亲时败给她的父亲，从而逃往中原，学得一身武功，并教了个汉人徒弟马家骏——也就是一直假扮叶老丈的人。华辉为了报复哈萨克人，曾让马家俊在井水中下毒，马家骏不忍心，先下手刺伤他，自此他就在此保护迷宫。如今师徒二人一场激战，双双伤重丧命。所谓迷宫之中的宝物，都是中原到处可见的纸、笔、围棋、七弦琴等等。\\n李文秀为关怀、照料自己的两位亲人的死而伤心，更为自己所爱的苏普爱别人而伤心，她只有骑着白马，回到中原，今后的路，还不知道向何方。\\n小说并不侧重武功的描写，似乎表达一种意念：人人追求的东西，往往并不一珍贵；而把握住自己所有的幸福，才是人世间难得的境界。这个让人唏嘘的故事，说穿了便觉其中无奈，正如李文秀所说：“你心里真正喜欢的，偏偏得不到，别人硬要给你的，就算好得不得了，我不喜欢，终', 'https://img3.doubanio.com/lpic/s2655602.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 78, '飞狐外传(上下)', '金庸', '平装', '三联书店', '23.00元', 618, '9787108012630', '《飞狐外传》作者是现代著名作家金庸，著于1960年，是《雪山飞狐》的前传。该书主要是讲述《雪山飞狐》主人公胡斐的成长历程.以主人公胡斐除暴安良为故事的中心;讲述了胡斐为追杀凤天南在路上所发生的一切.特别是主人公与两位女性所发生的恋爱关系,让人觉得惋惜与无奈.体现出江湖一代大侠在爱情面前是那样的脆弱与无奈.该书现收录在《金庸作品集》中。', 'https://img1.doubanio.com/lpic/s2157327.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 79, '雪山飞狐', '金庸', '平装', '三联书店', '0', 337, '9787108012548', '本书与金庸另一部小说《飞狐外传》情节相关联，但又各自独立。故事发生在清代乾隆时期的关外。饮马川陶百岁、陶子安父子从雪山中挖出一件宝物，封于铁盒之中。北京平通镖局总镖头熊元献带一伙人来抢夺，却被天龙门北宗阮士中、曹云奇、田青文与南宗殷吉劫去。大家拼打之间，一个名叫宝树的丑陋和尚赶到。宝树强“请”众人来到一高耸入云的玉笔峰山庄做客。因山庄主杜希盂外出未归，客人吃饭闲聊。\\n原来庄主邀请武林高手在此会一位盖世英雄——雪山飞狐胡斐。午前胡斐派二童子送信，称午间践约。玉笔峰上众人重新争夺铁盒，宝树倚强将铁盒持在手中，令人打开，内装一柄宝刀。\\n宝树谈起宝刀的来历，继而，分别由宝树、金面佛大侠苗人凤之女苗若兰、平阿四及陶百岁之口讲述了与此相关的一段武林往事。\\n此宝刀乃闯王李自成之遗物。闯王兵败时，身边有胡苗范田四大侍卫。闯王被困九宫山时，派苗范田三人去求救援，胡侍卫护卫闯王。但救援未到、敌兵先至，胡侍卫以一死卒充闯王献于清兵，然后将闯王安置一隐秘庙中为僧。胡侍卫因得清兵信任升官，苗范田三人却以为胡出卖闯王，定计报仇。三人行刺吴三桂时巧遇胡，不及胡陈明原委即将胡杀死。以后胡之子以实情告知三人，三人当众自刎。三人后代未知内情，苗范田遂与胡世代为仇。百余年来，四家子孙怨怨相报，无一代能得善终。\\n至胡一刀、苗人凤一代仍继先辈之仇。胡一刀护妻去南方生产，至唐官屯突然临产，此时恰与来此寻仇之苗人凤、田归农等人相逢。胡一刀遣人将当年实情告苗，却因田归农从中做梗而未达。胡苗遂有一场苦战。交战几日，二人仗义行侠之豪气与各怀之绝艺使对方顿生钦佩，虽为仇家却彼此视为知己。因田归农在二人比武之兵器上暗涂毒药，胡一刀以小伤毙命，胡夫人将幼子托与苗人凤，随夫自尽，田归农欲加害幼子，幸为平阿四救下，抚养长大，取名胡斐，按胡一刀遗下之刀谱练成绝技，称名武林，为雪山飞狐。\\n这日正午，胡斐如约至玉笔峰，峰上诸人因各怀鬼胎，惧怕胡斐，俱避内室。苗若兰镇定而出，接待胡斐，二人顿生爱恋。因庄主不在，胡斐暂避峰下。峰上之人谈及宝刀为当年闯王获明皇室宝之藏处指南，遂按宝刀所示，众人于峰后寻巨宝藏处。行前宝树将苗若兰点穴、田青文脱去若兰衣裤置其床上帐内。胡斐再至峰上，进内室，忽闻庄主约大内侍卫与武林高手来此围捕自己与苗人风，急避帐内，遭遇只着内衣之若兰。苗人凤来至峰上，不意中奸人之计被绑，胡斐勇出杀敌救苗人凤。但当苗人', 'https://img3.doubanio.com/lpic/s2157330.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 80, '金庸笔下的人生', '倪匡', '平装', '时代文艺出版社', '18.20', 312, '9788768755547', '本文分为上下两篇，上篇包括：总论、男女之爱、夫妻之情、兄弟朋友、师徒父子和后记。下篇包括：人生观、处世篇、人情篇、谈政篇、情趣篇和四大金庸小说评选。', 'https://img3.doubanio.com/lpic/s3231774.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 81, '金庸江湖志', '刘勃', '平装', '北京联合出版公司', '49.80元', 304, '9787559600486', '※ 读库作者刘勃趣品金庸。\\n※ 中华书局《掌故》杂志执行主编严晓星，畅销书作家填下乌贼诚意推荐。\\n本书是“读库”作家刘勃关于金庸小说的随笔杂谈结集。\\n全书分为三部分，第一部分是“武侠与金庸”，收录了《五岳剑派实力考》《少林达摩院的变迁》《杨过的水准问题》等“武评”文章；第二部分作者对金庸小说中的二十几个人物进行了精彩分析；第三部分“故事新说”中，作者借前两篇《苗人凤   》和《风清扬》抒发了自己的感慨；后一篇《趟子手》则借传统武侠小说的元素，书写了一些注定成不了大人物的年轻人。', 'https://img3.doubanio.com/lpic/s29480766.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 82, '连城诀', '金庸', '平装', '三联书店', '12.00', 329, '9787108012555', '本部书初发行是以「素心剑」为名，是金庸先生以小时候一段回忆为主而发展出来的故事，疼爱他的家中长工因为冤狱郁郁一生，心中的委屈至垂死才吐露于他。\\n「连城诀」以一部剑诀及其中的宝藏秘密揭露了人性贪婪的一面，写人的“坏“这本书可说是第一把交椅，狼心狗肺的丈夫，心机深疑心重的师 父，还有逼死自己女儿的父亲……憨直的乡下小子狄云，落入一个个圈套，失去了心爱的师妹，还有对人心的信赖。但是从这本书看来，当坏人也不是都很好过的，像有人半夜梦中爬起来堆尸砌墙，有人为了金银财宝发了狂……撇开这些可厌的事，丁典和凌霜华短暂的绿菊之恋，虽然淡淡如一阵幽香，却是全书最凄美的一段。', 'https://img3.doubanio.com/lpic/s27084783.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 83, '射鵰英雄傳', '金庸', NULL, '明河社', 'HK$160', 1623, '9789627461104', '', 'https://img3.doubanio.com/lpic/s1367124.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 84, '侠客行', '金庸', '平装', '三联书店', '38.00', 834, '9787108006707', '《侠客行》著于1965年，据说灵感和书名来自李白的诗作“古风五十九首”之《侠客行》。小说叙述的是一个懵懂少年石破天的江湖经历。\\n主人公石破天自小没名没姓，和一个他以为是自己母亲的女人，僻居于一座不知名的荒山上。那女人叫他做狗杂种，他便以为这就是他自己的名字。那女人脾气古怪，动辄打骂于他，他也习以为常。他从小学会了砍柴、做饭等种种家务，却大字不识一个，于世事、人心更是一无所知。一天那女人忽然不见了，他自小相伴的那条叫“阿黄”的狗也不见了，便出去到处寻找。结果人和狗都没找着，自己却迷了路。\\n当他来到一个叫侯监集的小镇上时，适逢许多武林人物为一枚玄铁令大动干戈。他是个小乞儿的样子，谁也没注意，却因为饥饿太甚，捡了个混战中撒落在地的烧饼吃，意外地得到了玄铁令。正在众人发现，各各威逼利诱之时，玄铁令的主人谢烟客适时赶到。将玄铁令夺回。但这个魔头恪于诺言，必须答应为持令者做一件事，他怕众人教唆这个小乞儿让他干不利于他的事，便连令带人一起携走。不料他想尽办法也不能让石破天求他一件事，石破天告诉他，母亲对他的唯一教诲，便是不管怎样也不能求人。他虽然是乞儿却从不乞讨，别人给他吃他就吃，别人不给，他实在饿了，便拿了就吃，他也不知道这叫偷，也不觉得有什么不对。\\n谢烟客无奈只好带他回自己隐居的摩天崖，途中石破天遇见几个武林人物围攻一个叫大悲老人的老头，他挺身而出，虽然没救成大悲老人，却在他临死之前做了他的朋友，得了他一套载有武功的泥人。到了摩天崖，谢烟客传授他两种极阴、极阳的内功，想让他走火入魔而死，以绝后患。\\n不料正在石破天阴阳交战，即将走火入魔的时候，长乐帮来人硬说石破天是他们的帮主，将他劫回帮中。帮中的医道高手贝海石将石破天救活，反而成就了他阴阳合一的无上内功。帮中人都认定他就是名叫石破天的帮主，他怎么解释也无济于事。后来他自己也怀疑起来，等到他结识了一个名叫丁当的女孩，那女孩指给他看，她从前在他肩头咬伤的疤痕时，他就更懵懂了。他喜欢丁当又不敢喜欢，因为他还不能确定自己到底是谁。\\n幸好在他最为难的时候，真的石破天被帮中人捉回。原来贝海石等人知道“狗杂种”不是真的石破天，但因他长相与石破天酷似，因此故意将错就错，让他冒名顶替，以替他们消解即将到来的灾难，而石破天肩上的伤疤，也是贝海石在他昏迷时用手术弄上去的。这时石破天已以帮主的身份接了侠客岛的赏善惩恶令，而在雪山派作了恶又冒', 'https://img3.doubanio.com/lpic/s24938374.jpg');
INSERT INTO `book` VALUES (1576678814, 1, 85, '神雕侠侣（套装共4册）', '金庸', '平装', '广州出版社', '96.00元', 1398, '9787546200705', '', 'https://img1.doubanio.com/lpic/s24574358.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 86, '鸳鸯刀', '金庸', NULL, NULL, NULL, NULL, '9785282111408', '小说叙述江湖上盛传的鸳鸯宝刀的秘密以及围绕它发生的故事。\\n武功不济却自视甚高的太岳四侠为给晋阳大侠萧半和祝寿，拦劫陕西西安府威信镖局为清廷保送的鸳鸯刀，被镖行武师所败；又欲抢夺林龙、任飞燕夫妻和书生袁冠南的行囊，谁知偷鸡不成蚀把米，反被袁冠南以言语诈去仅存的数两银子；好不容易等来一位年轻的姑娘骑着一匹骏马而来，却仍然不敌，幸好此女是萧半和的女儿萧中慧，听说四侠目的是给父亲拜寿，摘下头上的金钗送给他们作为礼物。萧中慧此行也为鸳鸯宝刀，甘亭镇汾安客店之中，她得知宝刀就在镖行人手中，暗自留神。\\n此时林玉龙夫妻、袁冠南、大内高手卓天雄都来到此处，尾随镖行。途中一场混战卓天雄技高一筹，点中林玉龙、任飞燕、萧中慧穴道，幸亏袁冠南用计惊走卓天雄，夺得鸳鸯刀，救出众人，四人逃到紫竹庵中，卓天雄追来，林玉龙夫妻把他们自己不好却威力很大的夫妻刀法传给袁、萧二人，二人用未学全的十二招刀法战胜卓天雄，保住了鸳鸯刀，而且由于并肩抗战，彼此互生情愫。萧半和生日这天，各路英雄豪杰都来庆贺，袁冠南献上鸳鸯刀，萧半和高兴之余，将女儿萧中慧许配给袁冠南。林玉龙、任飞燕把夫妻刀法全部传给袁、萧二人。喜庆筵上，袁冠南与萧半和之妻袁夫人母子相认，萧中慧伤心跑出，被卓天雄擒住。官兵围住萧府。一场混战，众英雄大败官兵，袁冠南救出萧中慧，二人再次联手，打伤卓天雄，众人一同退至中条山。山冈之上，萧半和说明真相：他本名萧义，为报父仇，早年入宫为太监，企图刺杀满清皇帝，却一直没能得手。后皇帝为夺鸳鸯宝刀，杀死保护宝刀的袁、杨两位大英雄，将他们的妻子儿女捕入牢中，萧义乘机救出二位夫人和儿女，奔逃之时，将袁冠南失落。为瞒清廷耳目，假和袁、杨二位扮作夫妻。萧中慧应叫杨中慧，是三湘大侠杨伯冲的女儿。正说之时，太岳四侠抬着卓天雄而来，夺回他从杨中慧手中抢去的鸳鸯刀。袁夫人把鸳鸯刀合在一起，只见上面分别刻着“仁者无敌”四个字，这就是鸳鸯刀无敌于天下的大秘密。\\n小说情节曲折语言诙谐，在不长的篇幅中展示了人物性格，塑造出几个不同的江湖侠士形象，可读性极强。虽为中篇，但仍不失为大手笔。\\n【作品评析】\\n[编辑本段]\\n1.倪匡谈金庸——《鸳鸯刀》\\n《鸳鸯刀》是金庸的另一短篇，情形和《白马啸西风》相类，在《鸳鸯刀》中，出色的是四个喜剧人物：太岳四侠——四个武功低微的小人物。\\n这是金庸小说中第一次出现这样的喜剧性质的人物，虽然在', 'https://img3.doubanio.com/lpic/s3157526.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 87, '越女剑', '金庸', 'Paperback', 'Simon & Schuster', 'USD 25.00', 256, '9780743294744', '《越女剑》，短篇武侠小说，金庸著，现收录于《金庸作品集》中，附于《侠客行》之后。', 'https://img3.doubanio.com/lpic/s3388613.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 88, '神雕侠侣·金庸武侠全集评点本（全四册）', '金庸', NULL, '文化艺术出版社', '92', NULL, '9787750391763', '《神雕侠侣》就是《射雕英雄传》的“后传”或“续书”，那又未免只知其一，不知其二了。因为，（一）《神雕侠侣》中虽然仍有郭靖、黄蓉、东邪西毒南帝北丐及全真七子、老顽童等老熟人的面孔及其活动线索，但它的主人公却是杨过、小龙女及郭芙、郭襄、武郭儒、武修文、耶律齐等一班新人。小说的故事情节是以新人的故事为主体的。（二）更重要的是，无论内容或形式、创作模式或主题思想，《神雕侠侣》都与《射雕英雄传》大不相同。在某种意义上，可以说，《神雕侠侣》标志着金庸武侠小说创作的一次（也是第一次）重大转折。', 'https://img3.doubanio.com/lpic/s1583726.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 89, '九阴九阳', '金庸新', '平装', '长春出版社', '13.50元', 740, '9787805738161', '威阳古道上，有五入勒马缓缓而行，两位老者，一对十年夫妇和一个十五六岁的少年。两名老者是武当宋远桥，张松溪，中年夫妇是殷梨亭、杨不悔夫妇，少年是他们的爱子殷融阳，近些年，武当派声名更盛，如日中天，派中弟子遍布中原，势力之雄除少林外，已无抗手。宋远桥、张松溪、殷梨亭三侠更是声名籍甚，派中有事，其座下弟子已能代师服劳，是以近些年来，江湖上难得见到他们的行踪，此番三侠联袂下山，分明是有大事发生。\\n第一回九阴白骨现江湖 第二回天师顽女洞室缘\\n第三回老仆忠义贯白日 第四回黑白追杀逢知已\\n第五回恩仇茫茫无处觅 第六回XXXXXXXXXXXXXX\\n第七回身陷华山做掌门 第八回群雄共计讨少林\\n第九回九阴真经冥冥去 第十回少年心性闯少林\\n第十一回以阳克阴破奸谋 第十二回难除大理风流根\\n第十三回陡振雄风败幅王 第十四回英雄大会九阴功\\n第十五回情援明月又乘龙 第十六回玄冥淫恶天理彰\\n第十七回天龙绝学复见光 第十八回龙虎交合融阴阳\\n第十九回三女同峰意参商 第二十回血海深仇得雪偿\\n第二十一回起死回天仗一阳 第二十二回举目天涯何惶惶\\n第二十三回九阴九阳争高强 第二十四回昆仑三挫少林芒\\n第二十五回怒惩天师昭日月 第二十六回子羽大义存武当\\n第二十七回明教武林重启衅 第二十八回玉门关外莽苍苍\\n第二十九回龙战于野血玄黄 第三十回百劫魂归浩气扬\\n第卅一回真人微言化苍桑', 'https://img3.doubanio.com/lpic/s2676504.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 90, '诸子百家看金庸Ⅰ', '三毛 冯其庸等', '平装', '重庆大学出版社', '24.00元', 196, '9787562447313', '金庸小说是与历史结合的武侠小说，也是一部武侠小说的当代传奇。众多著名作家、学者各抒己见，各逞才情，“射雕之卷”讲射雕英雄的悲剧，大拙对大巧的郭靖与黄蓉；“神雕之卷”讲各个人物的形态，天残地缺的爱情；“倚天之卷”中谈到善恶的边界，“风行之卷”谈到金庸小说出版、发行的“武林盛事”，等等。书中文体不限，论文、奇论、随想、考证，兼容并包，充分呈现了金庸小说在华语世界的影响力。', 'https://img3.doubanio.com/lpic/s3444063.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 91, '金庸小说论稿', '严家炎', NULL, '北京大学', '16.00元', 237, '9787301040065', '北京大学严家炎教授的“金庸小说研究”课饮誉北大讲坛，对金庸研究的合法化起到了重要作用。《金庸小说论稿》全方位地探讨金庸小说，首次披露了许多珍贵资料和重要事实，对了解金庸其人、其文极有帮助。本书是第一部从学理上研究金庸小说的专著。', 'https://img3.doubanio.com/lpic/s23787643.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 92, '三看金庸小说', '倪匡', '平装', '重庆大学出版社', '20.00元', 192, '9787562447269', '本书是倪匡对金庸作品《笑傲江湖》、《鹿鼎记》的专题评论。倪匡时而移步于武林人物之间嬉笑怒骂，时而跳脱出来赞叹金庸文笔之奇之幻，将韦小宝、令狐冲两个“绝顶人物”之洒脱写得活灵活现，同时也再次说明《鹿鼎记》在金庸小说中排行第一的理由。', 'https://img3.doubanio.com/lpic/s3443744.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 93, '金庸笔下的男女', '倪匡', '平装', '时代文艺出版社', '15.80', 252, '9787538768855', '', 'https://img1.doubanio.com/lpic/s3085407.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 94, '金庸小说赏析', '陈墨', '精装', '百花洲文艺出版社', '14.8', 392, '9787805790244', '本书是“金庸小说研究系列”之一。研究当今的武侠小说，不能不研究金庸。研究和评论金庸，对于提高武侠小说的创作水平，提高广大武侠小说的读者的鉴赏水平，也是十分必要，且意义深远的。《金庸小说赏析》可以说是研究金庸武侠小说的一项基础工程.正是从根本入手,本书对于引导读者读懂金庸，提高他们的鉴赏水平，无疑是有帮助的。对于那些抱成见或囿于偏见者，此书则是公然地为武侠小说“正名”。这于文学，于读者都该是有积极意', 'https://img1.doubanio.com/lpic/s25996248.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 95, '陈墨评金庸', '陈墨', '平装', '东方出版社', '36.00元', 606, '9787506032117', '《艺术金庸》主要内容：金庸的小说确确实实、地地道道的是武侠小说、通俗文学、娱乐游戏，其中充斥了虚构夸张、刀光剑影、奇幻怪诞。金庸自己也说他写小说是“自娱而且娱人”，是写着玩的，让人看着玩儿的。\\n但是金庸的小说又确确实实、地地道道的玩出了高水平，玩出了新花样，玩出了高境界，玩出了巨大的艺术成就。\\n问题便在这里了。我们必须证明：游戏可以是艺术，或艺术可以是游戏。否则我们的研究也就不大好“玩儿”啦。\\n这就牵涉到上面所说的第二个难点：中国人的文化观念的难点。\\n中国是一大文明古国，全世界了解中国人、尤其是了解中国汉民族的人，都知道中国汉民族是一个老成持重、严肃端庄的民族，这是一个少年老成的民族。至少这个民族的理想人格是老成持重、严肃端庄、少年老成的。在这个民族的历史上，甚至在这个民族的远古神话与传说中，酒神及其酒神精神是不存在的。这个民族甚至很少有真正意义上的神话，甚至自它的幼年时期开始，便学会了用理智的、现实的、成熟的成年人的目光来打量这个世界。汉民族也没有童年史诗，“子不语怪力乱神”成了它的铭文。这个民族是不能欣赏游戏、不重视游戏、不承认游戏在人生及其社会生活中的地位和作用的。至少，在汉民族历史上，持有“正统”观念的社会高层人士是这样的。所以当小说这种东西开始出现后，汉民族的圣人孔子将它定性为：“君子不为也”。因为小说这种玩艺儿是街谈巷语，是引车卖浆者之流的一种娱乐形式，所以“君子不为”。同时也成了我们民族的文化观念的——正统的、主流的、占统治地位的文化观念的——核心因素。\\n这部《金庸小说艺术论》共分下列三卷：\\n一、叙事艺术论。\\n二、形象塑造论。\\n三、审美境界论。', 'https://img3.doubanio.com/lpic/s3322731.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 96, '四看金庸小说', '倪匡', '平装', '重庆大学出版社', '20.00元', 180, '9787562447276', '《射雕英雄传》和《神雕侠侣》一脉相承。通过条分缕析地回溯故事，倪匡为杨康翻案，指郭靖为“伪人”，揭露黄蓉的“奸诈”，贬黄药师的“刻意”，赞欧阳锋的“自恃”、洪七公的“痛快”。金庸小说的精彩与成败尽在其中。', 'https://img1.doubanio.com/lpic/s5984458.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 97, '鹿鼎记（全五册）', '金庸', NULL, '文化艺术出版社', '110', NULL, '9787750391770', '本书是对鹿鼎记的评点本，本书的内容包括纵横钩党清流祸  峭茜风期月旦评、绝世奇事传闻里  最好交情见面、符来袖里围方解  椎脱囊中事竟成、无迹可寻羚挂角  忘机相对鹤梳翎、金戈运启驱除会  玉匣书留想象间、可知今日怜才意  即是当时种树心、古来成败原关数  天下英难大可知、佳客偶逢如有约  盛名长恐见无因、琢磨颇望成全壁  激烈何须到碎琴、尽有狂言容数子  每从高会厕诸公\\n；春辞小院离离影  夜受轻衫漠漠香、语带滑稽吾是戏  弊清摘发尔如神、翻覆两家天假手  兴衰一劫局更新、放逐肯消亡国恨  岁时犹动楚人哀、关心风雨经联榻  轻命江山博壮游、粉麝余香衔语燕  佩环新鬼泣啼乌、法门猛叩无方便  疑网重开有譬如、金刚宝杵卫帝释  雕篆石碣敲破头陀、九州聚铁铸一字  百金立木招群魔、残碑日月看仍在  前辈风流许再攀；金剪无声云委地  宝钗有梦燕依人、老衲山中移漏处  佳人世处改妆时、天生才土定多癖  君与此图皆可传、爱河纵涸须千劫  苦海难量为一慈、乌飞白头窜帝子  马挟红粉啼宫娥、草木连天人骨白  关山满眼夕阳红等具体详细内容。', 'https://img1.doubanio.com/lpic/s2029787.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 98, '金庸小说情爱论', '陈墨著', '精装', '百花洲文艺出版社', '12.0', 308, '9787805797274', '本书是“金庸小说研究系列”之一。都知道金庸是一位武侠小说的大宗师，却很少有人知道他也是一位真正的言情圣手。他的小说不仅是刀光剑影的武侠天地，而且也是丰富而深邃的情爱世界。本书对金庸小说的情爱世界的严肃性、丰富性、深刻性和独创性进行了深刻的分析，发出独到的见解。', 'https://img3.doubanio.com/lpic/s2663130.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 99, '醉眼看金庸', '孔庆东', '平装', '中国社会科学出版社', '24.00', 329, '9787801064165', '本书主要介绍作为武侠小说作家的金庸，作为散文家的金庸，只好屈尊另就了。读者欲进一步详细了解金庸的生平事迹等，则坊间另有大部头的作品。\\n金庸小说人生的“短而全”是本书的一个追求，另一个追求是赏析的“真而美”。以独到的阅读眼光，以金庸每部作品中的精彩段落为例，然后投入赏析者的真情实感，用优美的文字加以评论和分析，本书似乎还是首次。\\n对金庸武侠小说的争论部分，我们的选择标准首先是学术性，而不是追求哗众取宠的市场性。因此，那些“酷评”和漫骂，那些吵架和群殴，那些网络上的泡沫文字，很遗憾地又失去了一次轻薄成名的机会。我想，也许会有好事者另编一本《大骂金庸》之类，以普渡那些可怜的众生的。', 'https://img1.doubanio.com/lpic/s1343219.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 100, '挑灯看剑话金庸', '戈革', '平装', '中华书局', '26.00元', 219, '9787101059854', '《挑灯看剑话金庸》是戈革先生的率性之作，以极具感情的笔触评析了金庸武侠小说的写作特点、情节模式、故事来源等问题。老夫读金庸的书，往往过颊即空、入口而化，如洪七公吃黄蓉所做的菜一样。吃菜之后，就得拿出点真东西来。洪七公是大行家，吃了人家的嘴短，只好挺心疼地把几招“降龙十八掌”教给那孩子的“靖哥哥”。今日老夫见猎心喜，也打出几招庄稼拳脚来，于是而成了这个小册子……走江湖卖艺之人不亦云乎，“行家看门道，力巴看热闹”，只不知天下之行家，也能从俺的拳脚中看出一点儿“门道”来否？', 'https://img3.doubanio.com/lpic/s2953816.jpg');
INSERT INTO `book` VALUES (1576678854, 1, 101, '金庸小说与中国文化', '陈墨', '精装', '百花洲文艺出版社', '22.00', 684, '9787805796338', '有95年12月版。與99年1月版封面不同。', 'https://img3.doubanio.com/lpic/s25369093.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 102, '我与金庸的战争', '迟宇宙', '平装', '青海人民出版社', '22.00', 422, '9787225020150', '我对金庸的颠覆刚刚开始。一本戏说金庸小说中所有重要人物的诡谲之书。最另类、最有意思、最出人意料，也可能是最有独创性的。说到底，金庸小说并不神秘，神秘的只是我们的生活为何会如此乏味。\\n迟宇宙，一个好人，男，1976年11月5日生，1998年毕业于北京大学中文系，同年南下广州，在《南方周末》做了两年记者。热爱金庸，扬言：对金庸的颠覆刚刚开始。更热爱的老婆。是国内最具影响力的记者之一，他精于调查性', 'https://img3.doubanio.com/lpic/s1398934.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 103, '金庸小说的情爱世界', '陈墨', NULL, '安徽文艺出版社', '6.40元', NULL, '9787539608211', '', 'https://img3.doubanio.com/lpic/s3892623.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 104, '天龙八部漫画', '金庸', '盒装', '浙江人民美术出版社', '315.00', 3272, '9787534025402', '由香港“漫画之父”黄玉郎创作的全彩色漫画版《天龙八部》（21卷本），是在内地出版发行的第一部彩色漫画版金庸小说，也是黄玉郎先生绘制的首部彩色漫画版金庸小说，金庸先生为漫画版题写了书名。\\n黄玉郎与武侠小说巨匠金庸的合作可追溯至1997年，当时，黄玉郎金庸先生达成协议，由金庸先生授权给黄玉郎领衔的“玉皇朝”，为其武侠小说《天龙八部》推出黑白版漫画书。金庸小说漫画版的出现，在香港兴起了武侠小说漫画化的热潮，日本漫画热潮也因此在香港逐步减退。\\n国家新闻出版总署组织的专家对彩色漫画版《天龙八部》给予了高度评价，认为“该漫画沿袭了黄玉郎创作的独有风格，画面精彩，塑造人物个性鲜明。整部作品根据金庸先生的《天龙八部》编绘而成，刀光剑影，情节曲折，在惩恶扬善的教义指引下充满正义，堪称黄玉郎的又一部武侠漫画力作”。', 'https://img3.doubanio.com/lpic/s4164265.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 105, '金庸笔下的文史典故（上下）', '陈志明', NULL, '东方', '66.00元', 620, '9787506028684', '《金庸笔下的文史典故》(上、下共二册)通过对金庸十五部小说里面的文史典故的梳理和笺释，帮助读者了解金庸作品中大量的文史典故的出处和背景。《金庸笔下的文史典故》(上)半部分内容包括了“飞、雪、连、天、射、白、鹿”七部小说中的文史典故，《金庸笔下的文史典故》(下 )半部分包括了“笑、书、神、侠、倚、碧、鸳”和《越女剑》八部小说的文史典故。这是国内金庸研究者中第一次有人从这个角度对金庸作品进行全面笺释，资料丰富，具有相当的工具性和收藏性。', 'https://img1.doubanio.com/lpic/s2906089.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 106, '金庸评传', '孔庆东', NULL, '重庆出版社', '22.00元', 237, '9787229002299', '《金庸评传》主要内容：金庸的读者是以亿来计算的，是全世界古往今来读者最多的作家。活着的时候读者就以亿来计算的作家，只有金庸一个人。金庸以他一个人的功力，就让武侠小说进入了千家万户普通的生活。一个小说家、一个文学家，你成功的标志是什么？是你的人物、你的语言进入日常生活，进入日常语言。', 'https://img1.doubanio.com/lpic/s5960468.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 107, '孔庆东品读金庸侠语', '孔庆东', NULL, '长江文艺出版社', '26.00元', 369, '9787535435545', '《孔庆东品读金庸侠语》作者孔庆东，金侠小说精华与醉侠会心品读的完美组合，浓缩一代武侠宗师金庸经典小说的华彩篇章，由北大醉侠孔庆东精心编选、导读，从拳脚、兵刃、暗器、奇功、爱情、仪表、政治、历史、风物等方面尽现武侠大师“语到极处”的风范，金侠醉侠双侠合璧，大师语言锦上添花。', 'https://img1.doubanio.com/lpic/s11082298.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 108, '金庸小说的文化意蕴', '曹布拉', '平装(无盘)', '浙江人民出版社', '18.0', 321, '9787213027666', '', 'https://img1.doubanio.com/lpic/s1161388.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 109, '金庸客栈·十年', '新浪网友', NULL, '中国友谊出版公司', '29.80元', 244, '9787505723436', '本书是新浪网金庸客栈论坛十周年文章的作品集。全书分为武侠、评论、小说三部分。\\n武侠部分是网友针对金庸武侠小说而创作的文章，包括《为什么说风波恶是条汉子？》、《阿碧——被爱情遗忘的金庸女子》、《阿朱死得莫名其妙——金庸最大的败笔》、《八部天龙，真爱永恒——略论阿紫的爱情》、《悲情岳灵姗》、《东方不败回忆录》、《郭靖的草包哲学》、《金庸笔下的江南意象》、《金庸的大侠和反政府武装》、《金庸男女子足球队》、《金庸武侠魔鬼词典》、《金庸武学十大破绽》、《至情至性——郭襄》等。\\n评论部分是网友对电影、小说或人物的评论性文章，其中包括《从<花样年华>到<笑傲江湖>》、《冷酷的杨德昌，漆黑的牯岭街》、《满怀失落的记忆——纪念香港电影续集的辉煌时代》、《讨伐电视剧》、《吾皇万岁万万岁》等。\\n小说部分精选了网友发表在金庸客栈论坛上的部分小说，其中包括《爬·玫瑰·手机》、《204班少年杀人事件》、《东厂故事》等。', 'https://img3.doubanio.com/lpic/s2604260.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 110, '倚天屠龙记（共百册）', '原著金庸，漫画马荣成', NULL, '天下出版有限公司', '8.80元', 198, '9787537135702', '《倚天屠龙记》，金庸武侠小说，著于1961年，是“射雕三部曲”系列第三部。该书以元末群雄纷起、江湖动荡为广阔背景，叙述武当弟子张无忌的江湖生涯，表现众武林豪杰质朴自然，形态各异的精神风貌，展现其不可替代的人格力量。', 'https://img1.doubanio.com/lpic/s26019009.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 111, '讀金庸偶得', '舒國治', '平装', '遠流出版社', '240元', NULL, '9789573261094', '金庸的武俠世界瑰奇迷人，他的讀者更是遍及全球，而金學的相關研究則不知幾凡。作家舒國治以獨特細膩的觀察，暢談金庸小說種種，雖是「偶得」，卻不失嚴謹。\\n本書從名義的斟酌、武藝小說的練功本質、金庸的武藝社會、金庸思想上的特色，到金庸的寫法，都有詳盡而精闢的分析。作者完成此書的時間距今雖已廿五年，卻絲毫不減損它的可讀性，又可以看到舒國治在三十歲以前的寫作風貌。\\n書前的「弁言」〈武俠小說及其世代〉，洋洋灑灑七千字，是一頁新式的武俠小說史，更為那段流逝的老時光作了深情而親切的注解。讀完這篇弁言，彷彿也與作者一同走過溫馨的武俠年代，那樣的感覺，就像小說中的人物如在眼前一般。不論是正襟危坐的讀，或閒散慵懶的讀，都會有不同的收穫。對比幾個世代的金庸讀者，也許每個人都可以在裡面找到自己。\\n──摘自中副李炎、開卷董成瑜書介', 'https://img3.doubanio.com/lpic/s2587351.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 112, '金庸传', '辛磊', NULL, '湖北人民出版社', '30.00元', 259, '9787216051521', '凡是有华人的地方，就一定有金庸的武侠小说。\\n近40年来，新派武侠小说一代宗师金庸，其作品在风靡了全球华人世界的同时，也使中国特有的武侠小说创作达到了前所未有的高峰。\\n从获得诺贝尔奖的教授到贩夫走卒，从黄土高原到美利坚。\\n八十岁的金庸是我们这个时代的一个神话，有人说他是“文坛侠圣” ，有人称他为香港“良知的灯塔，”也有人认为他一钱不值。在本书中，你将看到他的理想、事业、婚姻……从各个侧面反映出历史的曲折和变化，他的思想与故事折射出大时代的星星点点。 “凡是有华人的地方，就一定有金庸的武侠小说。”近40年来，新派武侠小说一代宗师金庸，其作品在风靡了全球华人世界的同时，也使中国特有的武侠小说创作达到了前所未有的高峰。回首几十年的奋斗历程，金庸之深大、神秘，正构成了金庸的无穷魅力。 百年一金庸，金庸说不完，不妨听作者娓娓道来……', 'https://img3.doubanio.com/lpic/s6325410.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 113, '剑桥简明金庸武侠史', '新垣平', '平装', '长江文艺出版社', '32.80元', 472, '9787535466716', '本书是关于中国武侠世界的一部虚拟历史研究。以金庸武侠是真实历史的一部分为前提展开演绎。本身以十五部金庸小说、唐宋传奇及各时期民间传说为基础构成的连贯武侠史为重心，结合了政治和社会历史的研究，重述了自商朝到清末三千年间的全部中国历史。\\n书中考察了武术、江湖和门派等在历史上的起源、发展和嬗变，以历史叙事的方式整理了越女、萧峰、郭靖、张无忌、韦小宝等大量金庸小说中人物的事迹。本书综合了各部作品中的线索，探讨了少林、武当、丐帮、明教、天地会等武术组织的由来和兴衰，并解答了许多原著中未曾回答的问题。另一方面，从成吉思汗、朱元璋、康熙和乾隆等帝王，到岳飞、王保保、李自成、陈圆圆、鳌拜、噶尔丹、福康安等数百位大小历史人物的生平和事迹，也都放在这部武侠史的框架内进行演绎。', 'https://img3.doubanio.com/lpic/s26821883.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 114, '越女剣―傑作武侠中篇集', '金庸', '単行本', '德間書店', 'JPY 1836', 327, '9784198613631', '日文版。\\n包括3篇金庸小說日譯：白馬嘯西風、鴛鴦刀、越女劍。', 'https://img3.doubanio.com/lpic/s28100231.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 115, '金庸师承考', '刘国重', '平装', '北京联合出版公司', '49.80元', 328, '9787559600493', '※ 网络金庸小说研究家刘国重最新力作。\\n※ 中国社会科学院文学研究所研究员施爱东，资深媒体人胡文辉、石扉客推荐。\\n在《天方夜谭》会情郎的刀白凤和“梦姑”；借用达达尼昂“活盾牌”的向问天；烈火中高歌的老太婆乌尔莉佳和李莫愁；大理国“三公”与《狄公案》；“琴剑双侠”与“靖蓉双侠”……\\n本书从大量中外名著中爬罗剔抉，寻找金庸作品中借鉴、吸收的古今中外著作中的实例，揭示出金庸小说素材的源泉，并以一篇篇生动有趣的文章呈现出来。', 'https://img1.doubanio.com/lpic/s29480767.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 116, '金庸评传', '孔庆东', '平装', '郑州大学出版社', '20.0', 214, '9787810489799', '壹 骚人阁笔费评章\\n——金庸的意义\\n贰 金庸的文化渊源\\n——中国武侠小说概貌\\n叁 鲲鹏展翅逍遥游\\n——金庸的生平\\n肆 满目琳琅的一生\\n——金庸作品的年轮\\n伍 剑气碧烟横\\n——金庸武侠小说评析\\n陆 道可道，非常道\\n——金庸的艺术成就', 'https://img3.doubanio.com/lpic/s1431996.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 117, '金庸与明报', '张圭阳', '平装', '湖北人民出版社', '28.00元', 293, '9787216052702', '金庸，作为武侠小说领域的一代宗师，可谓誉满中华深受广大读者的喜爱；但作为一代报人，却为人知之甚少。其实，正如金庸自己所言《明报》才是他毕生的事业与声誉。本书截取1959年金庸离开长城电影公司创办《明报》，到1994年辞去明报企业集团荣誉主席的这段时间来研究。详细阐述了《明报》从一份都市小报伴随香港和大陆的时局变幻发展壮大为华文领域一份政论性大报的过程，以及此过程中，特别是三次大的发展机遇面前，金庸对《明报》的驾驭和作用。不仅如此，本书还以《明报》为中心，结合上溯下延的报业资料，较为翔实地描绘了这个时段香港其他中文报纸的办报特点和香港中文报业的整体发展状况，很好地填补了香港作为中国现当代中文报业中心断代史系统研究领域的空白。.', 'https://img1.doubanio.com/lpic/s27479919.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 118, '金庸识小录', '严晓星', '精装', '中华书局', '27.00元', 231, '9787101085228', '作者酷爱乱读书，尤好金庸小说，阅读中随手考掘故实，索隐发微，出入于文学、历史、风俗、博物、西学之间，虽以短小的札记体裁写出，但能免于陈言，而富于趣味性与知识性。论者以为其价值实远在坊间所谓“金学”论著之上。本书的大部分篇章十年前即已在网上流传，以其令人耳目一新的写法，拥有众多的读者和良好的口碑，一时模仿者甚众。这是作者加以增订后的首次结集出版。\\n书中所附四万字的《金庸年谱简编》，系在作者自撰的三十万字的《金庸年谱长编》基础上缩写而成，是迄今最为详实的金庸生平系年。', 'https://img1.doubanio.com/lpic/s11131679.jpg');
INSERT INTO `book` VALUES (1576678889, 1, 119, '金庸武侠小说全集（电子图书二碟装）', '金庸', '盒装精', '青苹果数据中心', '48.00', NULL, '9787900073655', '这两张光盘收入了金庸的全部15部武侠小说，即：\\n宝刀相间欢，柔情恨无常－－《飞狐外传》\\n人间自有真情在－－《雪山飞狐》\\n拔剑四顾心茫然－－《连城诀》\\n无人不冤，有情皆孽――《天龙八部》\\n为草莽英雄作“春秋”－－《射雕英雄传》\\n天铃鸟依然在唱歌－－《白马啸西风》\\n非武非侠，亦史亦奇－－《鹿鼎记》，\\n达非兼济天下，穷难独善其身－－《笑傲江湖》\\n开头是错，结尾还是错－－《书剑恩仇录》\\n问世间，情为何物－－《神雕侠侣》\\n叙事迷宫和寓言世界－－《侠客行》\\n从英雄神曲到人性传奇－－《倚天屠龙记》\\n乱世情仇乱世衰－－《碧血剑》\\n趣中有趣曲里藏曲－－《鸳鸯刀》。\\n历史情怀与人性悲歌－－《越女剑》\\n其中《白马啸西风》、《鸳鸯刀》、《越女剑》许多读者尚未见过！', 'https://img3.doubanio.com/lpic/s1178953.jpg');

SET FOREIGN_KEY_CHECKS = 1;
